<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>True</IsPackable>
        <PackageId>Hardened.Amz.CloudWatch.Dashboards</PackageId>
        <Authors>Ian Johnson</Authors>
        <PackageTags>Hardened.Framework</PackageTags>
        <PackageProjectUrl>https://github.com/ipjohnson-org/Hardened.Amz</PackageProjectUrl>
        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://github.com/ipjohnson-org/Hardened.Amz</RepositoryUrl>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Hardened.Library.SourceGenerator" Version="0.2.0-*" />
        <PackageReference Include="Hardened.Requests.Abstract" Version="0.2.0-*" />
        <PackageReference Include="Hardened.Shared.Runtime" Version="0.2.0-*" />
        <PackageReference Include="Hardened.Templates.Abstract" Version="0.2.0-*" />
        <PackageReference Include="Hardened.Templates.Runtime" Version="0.2.0-*" />
    </ItemGroup>

</Project>
