using Hardened.Idl;
using Hardened.Generation;
using Hardened.Generation.Models;
using Hardened.Smithy.BuildTask.Parsing;
using Xunit;

namespace Hardened.Smithy.BuildTask.Tests;

/// <summary>
/// awsJson1_0: the second protocol, and the one that proves the seam.
/// </summary>
/// <remarks>
/// <para>
/// It is an RPC protocol wearing HTTP as an envelope - every operation is <c>POST /</c> and which
/// one it is comes from an <c>X-Amz-Target</c> header. So it exercises the parts of the model that
/// restJson1 never does: an operation whose path and verb distinguish nothing, a dispatch key that
/// distinguishes everything, and binding traits the specification requires be ignored.
/// </para>
/// <para>
/// The fixture is generated by the real CLI against a model declaring a maven dependency on
/// smithy-aws-traits, so its AST carries thirty-five shapes from that dependency beside the eight
/// the model declares. That is not incidental - it is the case the trait-definition filter exists
/// for, and it only occurs with a dependency.
/// </para>
/// </remarks>
public class AwsJsonProtocolTests {

    private static string Fixture(string name) =>
        File.ReadAllText(Path.Combine(AppContext.BaseDirectory, "Fixtures", name));

    private static ServiceSpecModel Parse() {
        var diagnostics = new List<string>();
        var model = SmithySpecParser.Parse(Fixture("bank-awsjson.json"), "bank", diagnostics);

        Assert.NotNull(model);

        return model!;
    }

    private static OperationModel Operation(ServiceSpecModel model, string operationId) =>
        Assert.Single(model.Services[0].Operations, o => o.OperationId == operationId);

    [Fact]
    public void Parse_AcceptsAwsJsonRatherThanRefusingIt() {
        var model = Parse();

        Assert.Equal("Bank", Assert.Single(model.Services).Tag);
        Assert.Equal(2, model.Services[0].Operations.Count);
    }

    [Fact]
    public void Parse_PutsTheDispatchHeaderOnTheService() {
        Assert.Equal("X-Amz-Target", Assert.Single(Parse().Services).DispatchHeader);
    }

    /// <summary>
    /// Every operation is POST / - the route distinguishes nothing, which is exactly why the
    /// dispatch key has to.
    /// </summary>
    [Fact]
    public void Parse_SendsEveryOperationToOneRoute() {
        var model = Parse();

        foreach (var operation in model.Services[0].Operations) {
            Assert.Equal("/", operation.Path);
            Assert.Equal("POST", operation.HttpMethod);
        }
    }

    /// <summary>The header value the protocol specifies: <c>Service.Operation</c>.</summary>
    [Fact]
    public void Parse_NamesEachOperationByServiceAndOperation() {
        var model = Parse();

        Assert.Equal("Bank.GetBalance", Operation(model, "GetBalance").DispatchKey);
        Assert.Equal("Bank.Transfer", Operation(model, "Transfer").DispatchKey);
    }

    [Fact]
    public void Parse_UsesTheProtocolsContentType() {
        var transfer = Operation(Parse(), "Transfer");

        Assert.Equal("application/x-amz-json-1.0", transfer.RequestBodyContentType);
        Assert.Equal("application/x-amz-json-1.0", transfer.ResponseContentType);
    }

    /// <summary>
    /// No member is bound to a path, query or header, so every one of them is the body - which is
    /// simpler than restJson1 rather than harder.
    /// </summary>
    [Fact]
    public void Parse_MakesTheWholeInputStructureTheBody() {
        var transfer = Operation(Parse(), "Transfer");

        Assert.Empty(transfer.Parameters);
        Assert.Equal("TransferInput", TypeMapper.GetRefName(transfer.RequestBodyRef!));
        Assert.Equal(3, transfer.RequestBodyProperties.Count);
    }

    [Fact]
    public void Parse_ReadsConstraintsTheSameWayUnderEitherProtocol() {
        var amount = Assert.Single(
            Operation(Parse(), "Transfer").RequestBodyProperties, p => p.Name == "amountCents");

        Assert.Equal(1m, amount.Minimum);
    }

    /// <summary>
    /// The dependency's trait definitions are shapes in this AST - thirty-five of them - and not one
    /// becomes a generated type.
    /// </summary>
    [Fact]
    public void Parse_GeneratesNothingForDependencyTraitShapes() {
        var model = Parse();

        Assert.DoesNotContain(model.Schemas, s => s.Name is "arn" or "clientEndpointDiscovery");
        Assert.All(model.Schemas, s => Assert.DoesNotContain(s.Name, "#"));
        Assert.Contains(model.Schemas, s => s.Name == "TransferInput");
    }

    /// <summary>
    /// The specification says HTTP binding traits "MUST be ignored if they are present", so a model
    /// carrying both a dispatch protocol and an @http trait is well formed - and this is what
    /// ignoring them means, rather than a conflict to report.
    /// </summary>
    [Fact]
    public void Parse_IgnoresHttpBindingTraitsUnderADispatchProtocol() {
        var diagnostics = new List<string>();

        var ast = """
                  { "smithy": "2.0", "shapes": {
                      "com.example#Svc": {
                        "type": "service", "version": "1",
                        "operations": [ { "target": "com.example#Op" } ],
                        "traits": { "aws.protocols#awsJson1_0": {} } },
                      "com.example#Op": {
                        "type": "operation",
                        "input": { "target": "com.example#In" },
                        "traits": { "smithy.api#http": { "method": "GET", "uri": "/ignored/{id}", "code": 204 } } },
                      "com.example#In": {
                        "type": "structure",
                        "members": {
                          "id": {
                            "target": "smithy.api#String",
                            "traits": { "smithy.api#httpLabel": {}, "smithy.api#required": {} } } } } } }
                  """;

        var model = SmithySpecParser.Parse(ast, "ignored", diagnostics);

        Assert.NotNull(model);

        var operation = Assert.Single(model!.Services[0].Operations);

        Assert.Equal("/", operation.Path);
        Assert.Equal("POST", operation.HttpMethod);
        Assert.Empty(operation.Parameters);
        Assert.Single(operation.RequestBodyProperties);
    }

    /// <summary>
    /// A model with no protocol trait still routes, which is what keeps restJson1 and hand-written
    /// models working unchanged.
    /// </summary>
    [Fact]
    public void Parse_LeavesRoutedOperationsWithoutADispatchKey() {
        var diagnostics = new List<string>();
        var model = SmithySpecParser.Parse(Fixture("petstore.json"), "petstore", diagnostics);

        Assert.NotNull(model);
        Assert.Null(Assert.Single(model!.Services).DispatchHeader);
        Assert.All(model.Services[0].Operations, o => Assert.Null(o.DispatchKey));
    }

    /// <summary>
    /// awsJson serializes an error exactly like a success and distinguishes it by one body field,
    /// so the error shape carries it.
    /// </summary>
    /// <remarks>
    /// The specification says a server should send the <em>full</em> shape id, and that a client
    /// takes only what follows a <c>#</c> - so the qualified form is what both halves agree on.
    /// </remarks>
    [Fact]
    public void Parse_GivesErrorShapesATypeDiscriminator() {
        var notFound = Assert.Single(Parse().Schemas, s => s.Name == "AccountNotFound");

        var discriminator = Assert.Single(notFound.Properties, p => p.Name == "__type");

        Assert.Equal("com.example.bank#AccountNotFound", discriminator.Default);
        Assert.Equal("string", discriminator.Type);
        Assert.False(discriminator.IsRequired);
    }

    /// <summary>
    /// It has a default, so it lands after every required member - which is what keeps the record's
    /// positional constructor and the resolver's parameter metadata agreeing by index.
    /// </summary>
    [Fact]
    public void Parse_PutsTheDiscriminatorAfterTheRequiredMembers() {
        var notFound = Assert.Single(Parse().Schemas, s => s.Name == "AccountNotFound");

        Assert.True(notFound.Properties.Find(p => p.Name == "__type")!.HasDefault);
        Assert.False(notFound.Properties.Find(p => p.Name == "message")!.HasDefault);
    }

    /// <summary>One error shape is routinely thrown by several operations; each reaches this.</summary>
    [Fact]
    public void Parse_AddsTheDiscriminatorOnlyOnce() {
        var notFound = Assert.Single(Parse().Schemas, s => s.Name == "AccountNotFound");

        Assert.Single(notFound.Properties, p => p.Name == "__type");
    }

    /// <summary>
    /// A routed protocol says which error it is with a status code, so the field would be noise.
    /// </summary>
    [Fact]
    public void Parse_LeavesRoutedErrorShapesAlone() {
        var diagnostics = new List<string>();
        var model = SmithySpecParser.Parse(Fixture("petstore.json"), "petstore", diagnostics);

        var notFound = Assert.Single(model!.Schemas, s => s.Name == "PetNotFound");

        Assert.DoesNotContain(notFound.Properties, p => p.Name == "__type");
    }

    /// <summary>
    /// @httpError is an HTTP binding trait, and a dispatch protocol requires those be ignored - so
    /// @error's client/server is what decides the status.
    /// </summary>
    [Fact]
    public void Parse_IgnoresHttpErrorUnderADispatchProtocol() {
        var diagnostics = new List<string>();

        var ast = """
                  { "smithy": "2.0", "shapes": {
                      "com.example#Svc": {
                        "type": "service", "version": "1",
                        "operations": [ { "target": "com.example#Op" } ],
                        "traits": { "aws.protocols#awsJson1_0": {} } },
                      "com.example#Op": {
                        "type": "operation",
                        "errors": [ { "target": "com.example#Boom" } ] },
                      "com.example#Boom": {
                        "type": "structure", "members": {},
                        "traits": {
                          "smithy.api#error": "client",
                          "smithy.api#httpError": 418 } } } }
                  """;

        var model = SmithySpecParser.Parse(ast, "httperror", diagnostics);

        Assert.NotNull(model);

        var error = Assert.Single(model!.Services[0].Operations[0].ErrorResponses);

        Assert.Equal(400, error.StatusCode);
    }

    [Fact]
    public void Parse_StillRefusesAProtocolItCannotSerialise() {
        var diagnostics = new List<string>();

        var ast = """
                  { "smithy": "2.0", "shapes": {
                      "com.example#Svc": {
                        "type": "service", "version": "1",
                        "traits": { "aws.protocols#restXml": {} } } } }
                  """;

        Assert.Null(SmithySpecParser.Parse(ast, "restxml", diagnostics));
        Assert.Contains(diagnostics, d => d.Contains("XML"));
    }

    /// <summary>
    /// The dispatch key is part of a handler's identity, so it has to survive the model file - the
    /// generator reads that, not the AST.
    /// </summary>
    [Fact]
    public void Parse_CarriesDispatchThroughTheSerializedModel() {
        var written = SpecModelSerializer.Write(Parse());
        var round = SpecModelSerializer.Read(written);

        Assert.Equal("X-Amz-Target", Assert.Single(round.Services).DispatchHeader);
        Assert.Equal("Bank.GetBalance", Operation(round, "GetBalance").DispatchKey);
    }
}
