<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Hardened.Shared.Testing" Version="0.2.0-Alpha11" />
      <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.0" />
      <PackageReference Include="xunit" Version="2.9.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Lambda\Sqs\Hardened.Amz.Function.Sqs.Runtime\Hardened.Amz.Function.Sqs.Runtime.csproj" />
      <ProjectReference Include="..\Lambda\Sqs\Hardened.Amz.Function.Sqs.Testing\Hardened.Amz.Function.Sqs.Testing.csproj" />
      <ProjectReference Include="..\SqsTest\SqsTest.csproj" />
    </ItemGroup>

</Project>
