<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(HardenedTargetFramework)</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Hardened.Requests.Caching.Memory\Hardened.Requests.Caching.Memory.csproj"/>
    </ItemGroup>

</Project>
