<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(HardenedTargetFramework)</TargetFramework>
        <Description>Runs Hardened tests against a real DynamoDB in a container, rather than a fake.</Description>
        <IsPackable>true</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\Shared\Hardened.Shared.Testing\Hardened.Shared.Testing.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Testcontainers.DynamoDb" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Hardened.Aws.DynamoDbClient\Hardened.Aws.DynamoDbClient.csproj" />
    </ItemGroup>

</Project>
