<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Description>Mustache-style template engine for Hardened, with templates compiled to C# at build time.</Description>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>True</IsPackable>
        <PackageId>Hardened.Templates.Runtime</PackageId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="DependencyModules.Runtime" Version="1.0.0-rc9220" />
        <PackageReference Include="DependencyModules.SourceGenerator" Version="1.0.0-rc9220" OutputItemType="Analyzer" ReferenceOutputAssembly="false" PrivateAssets="all" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.1" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.1" />
        <PackageReference Include="Microsoft.Extensions.Primitives" Version="8.0.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Requests\Hardened.Requests.Abstract\Hardened.Requests.Abstract.csproj"/>
        <ProjectReference Include="..\Hardened.Templates.Abstract\Hardened.Templates.Abstract.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Helpers\Json"/>
        <Folder Include="Models\"/>
    </ItemGroup>

</Project>
