name: update-dependencies
on:
  workflow_run:
    workflows: [build-package]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ['FriendsWithRecipes.Common']
        
    steps:
    - uses: passeidireto/trigger-external-workflow-action@main
      env:
        PAYLOAD_REBUILD: "false"
        PAYLOAD_BRANCH: ${{github.ref}}
      with:
        repository: ipjohnson-org/${{ matrix.repo }}
        event: update_dep
        github_pat: ${{ secrets.UPDATE_DEPENDENCY_PAT }}
