<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(HardenedTargetFramework)</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="NSubstitute"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Hardened.Web.StaticContent\Hardened.Web.StaticContent.csproj"/>
    </ItemGroup>

</Project>
