using Hardened.OpenApi.SourceGenerator.Models;

namespace Hardened.OpenApi.SourceGenerator.Emitters;

internal static class ControllerWrapperEmitter {
    public static string Emit(ServiceModel service, string rootNs) {
        var controllerNs = rootNs + ".Generated";
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"using {rootNs}.Models;");
        sb.AppendLine($"using {rootNs}.Services;");
        sb.AppendLine();
        sb.AppendLine($"namespace {controllerNs};");
        sb.AppendLine();

        var interfaceName = NamingHelper.ToInterfaceName(service.Tag);
        var controllerName = NamingHelper.ToControllerName(service.Tag);

        sb.AppendLine($"public class {controllerName}");
        sb.AppendLine("{");
        sb.AppendLine($"    private readonly {interfaceName} _service;");
        sb.AppendLine();
        sb.AppendLine($"    public {controllerName}({interfaceName} service)");
        sb.AppendLine("    {");
        sb.AppendLine("        _service = service;");
        sb.AppendLine("    }");

        foreach (var op in service.Operations) {
            sb.AppendLine();
            var methodName = NamingHelper.ToMethodName(op.OperationId);
            var returnType = ServiceInterfaceEmitter.GetReturnType(op, rootNs);
            var parameters = ServiceInterfaceEmitter.GetParameterList(op, rootNs);
            var args = GetArgumentList(op);

            sb.AppendLine($"    public {returnType} {methodName}({parameters})");
            sb.AppendLine("    {");
            sb.AppendLine($"        return _service.{methodName}({args});");
            sb.AppendLine("    }");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GetArgumentList(OperationModel op) {
        var parts = new List<string>();

        foreach (var param in op.Parameters) {
            if (param.In == "path" || param.In == "query") {
                parts.Add(NamingHelper.ToParameterName(param.Name));
            }
        }

        if (op.RequestBodyRef != null || op.RequestBodyType != null) {
            parts.Add("body");
        }

        return string.Join(", ", parts);
    }
}
