using System.Text;
using Hardened.OpenApi.SourceGenerator.Models;

namespace Hardened.OpenApi.SourceGenerator.Emitters;

internal static class JsonTypeInfoEmitter {
    public static string Emit(List<SchemaModel> schemas, string ns, bool excludeFromCoverage = false) {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine("using System.Text.Json.Serialization.Metadata;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns}.Models;");
        sb.AppendLine();
        if (excludeFromCoverage) {
            sb.AppendLine("[System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        }
        sb.AppendLine("public sealed class OpenApiJsonTypeInfoResolver : IJsonTypeInfoResolver");
        sb.AppendLine("{");
        sb.AppendLine("    public static readonly OpenApiJsonTypeInfoResolver Instance = new();");
        sb.AppendLine();

        EmitGetTypeInfo(sb, schemas);

        foreach (var schema in schemas) {
            switch (schema.Kind) {
                case SchemaKind.Object:
                    EmitObjectTypeInfo(sb, schema, schemas);
                    break;
                case SchemaKind.Enum:
                    EmitEnumTypeInfo(sb, schema);
                    break;
            }
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitGetTypeInfo(StringBuilder sb, List<SchemaModel> schemas) {
        sb.AppendLine("    public JsonTypeInfo? GetTypeInfo(Type type, JsonSerializerOptions options)");
        sb.AppendLine("    {");

        foreach (var schema in schemas) {
            if (schema.Kind != SchemaKind.Object && schema.Kind != SchemaKind.Enum) continue;
            var typeName = NamingHelper.ToPascalCase(schema.Name);
            sb.AppendLine($"        if (type == typeof({typeName})) return Create{typeName}TypeInfo(options);");
        }

        EmitPrimitiveTypeEntries(sb);
        EmitCollectionTypeEntries(sb, schemas);

        sb.AppendLine("        return null;");
        sb.AppendLine("    }");
    }

    private static void EmitPrimitiveTypeEntries(StringBuilder sb) {
        sb.AppendLine();
        sb.AppendLine("        // Primitive types");
        sb.AppendLine("        if (type == typeof(string)) return JsonMetadataServices.CreateValueInfo<string>(options, JsonMetadataServices.StringConverter);");
        sb.AppendLine("        if (type == typeof(bool)) return JsonMetadataServices.CreateValueInfo<bool>(options, JsonMetadataServices.BooleanConverter);");
        sb.AppendLine("        if (type == typeof(int)) return JsonMetadataServices.CreateValueInfo<int>(options, JsonMetadataServices.Int32Converter);");
        sb.AppendLine("        if (type == typeof(uint)) return JsonMetadataServices.CreateValueInfo<uint>(options, JsonMetadataServices.UInt32Converter);");
        sb.AppendLine("        if (type == typeof(long)) return JsonMetadataServices.CreateValueInfo<long>(options, JsonMetadataServices.Int64Converter);");
        sb.AppendLine("        if (type == typeof(float)) return JsonMetadataServices.CreateValueInfo<float>(options, JsonMetadataServices.SingleConverter);");
        sb.AppendLine("        if (type == typeof(double)) return JsonMetadataServices.CreateValueInfo<double>(options, JsonMetadataServices.DoubleConverter);");
        sb.AppendLine("        if (type == typeof(DateTime)) return JsonMetadataServices.CreateValueInfo<DateTime>(options, JsonMetadataServices.DateTimeConverter);");
        sb.AppendLine("        if (type == typeof(DateOnly)) return JsonMetadataServices.CreateValueInfo<DateOnly>(options, JsonMetadataServices.DateOnlyConverter);");
        sb.AppendLine("        if (type == typeof(byte[])) return JsonMetadataServices.CreateValueInfo<byte[]>(options, JsonMetadataServices.ByteArrayConverter);");
        sb.AppendLine("        if (type == typeof(JsonElement)) return JsonMetadataServices.CreateValueInfo<JsonElement>(options, JsonMetadataServices.JsonElementConverter);");
        sb.AppendLine();
        sb.AppendLine("        // Nullable value types");
        sb.AppendLine("        if (type == typeof(bool?)) return JsonMetadataServices.CreateValueInfo<bool?>(options, JsonMetadataServices.GetNullableConverter<bool>(options));");
        sb.AppendLine("        if (type == typeof(int?)) return JsonMetadataServices.CreateValueInfo<int?>(options, JsonMetadataServices.GetNullableConverter<int>(options));");
        sb.AppendLine("        if (type == typeof(uint?)) return JsonMetadataServices.CreateValueInfo<uint?>(options, JsonMetadataServices.GetNullableConverter<uint>(options));");
        sb.AppendLine("        if (type == typeof(long?)) return JsonMetadataServices.CreateValueInfo<long?>(options, JsonMetadataServices.GetNullableConverter<long>(options));");
        sb.AppendLine("        if (type == typeof(float?)) return JsonMetadataServices.CreateValueInfo<float?>(options, JsonMetadataServices.GetNullableConverter<float>(options));");
        sb.AppendLine("        if (type == typeof(double?)) return JsonMetadataServices.CreateValueInfo<double?>(options, JsonMetadataServices.GetNullableConverter<double>(options));");
        sb.AppendLine("        if (type == typeof(DateTime?)) return JsonMetadataServices.CreateValueInfo<DateTime?>(options, JsonMetadataServices.GetNullableConverter<DateTime>(options));");
        sb.AppendLine("        if (type == typeof(DateOnly?)) return JsonMetadataServices.CreateValueInfo<DateOnly?>(options, JsonMetadataServices.GetNullableConverter<DateOnly>(options));");
        sb.AppendLine("        if (type == typeof(JsonElement?)) return JsonMetadataServices.CreateValueInfo<JsonElement?>(options, JsonMetadataServices.GetNullableConverter<JsonElement>(options));");
    }

    private static void EmitObjectTypeInfo(StringBuilder sb, SchemaModel schema, List<SchemaModel> allSchemas) {
        var typeName = NamingHelper.ToPascalCase(schema.Name);

        sb.AppendLine();
        sb.AppendLine($"    private static JsonTypeInfo<{typeName}> Create{typeName}TypeInfo(JsonSerializerOptions options)");
        sb.AppendLine("    {");

        if (schema.Properties.Count == 0) {
            sb.AppendLine($"        return JsonMetadataServices.CreateObjectInfo<{typeName}>(options, new JsonObjectInfoValues<{typeName}>");
            sb.AppendLine("        {");
            sb.AppendLine($"            ObjectCreator = static () => new {typeName}(),");
            sb.AppendLine("        });");
        } else {
            var sorted = schema.Properties.OrderByDescending(p => p.IsRequired).ToList();

            sb.AppendLine($"        return JsonMetadataServices.CreateObjectInfo<{typeName}>(options, new JsonObjectInfoValues<{typeName}>");
            sb.AppendLine("        {");

            // ObjectWithParameterizedConstructorCreator
            sb.AppendLine($"            ObjectWithParameterizedConstructorCreator = static args => new {typeName}(");
            for (var i = 0; i < sorted.Count; i++) {
                var prop = sorted[i];
                var castType = GetFullCSharpType(prop, allSchemas);
                var comma = i < sorted.Count - 1 ? "," : "),";
                sb.AppendLine($"                ({castType})args[{i}]{comma}");
            }

            // PropertyMetadataInitializer — captures options (non-static)
            sb.AppendLine("            PropertyMetadataInitializer = _ => new JsonPropertyInfo[]");
            sb.AppendLine("            {");
            for (var i = 0; i < sorted.Count; i++) {
                var prop = sorted[i];
                EmitPropertyInfo(sb, prop, typeName, allSchemas);
            }
            sb.AppendLine("            },");

            // ConstructorParameterMetadataInitializer
            sb.AppendLine("            ConstructorParameterMetadataInitializer = static () => new JsonParameterInfoValues[]");
            sb.AppendLine("            {");
            for (var i = 0; i < sorted.Count; i++) {
                var prop = sorted[i];
                EmitParameterInfo(sb, prop, i, allSchemas);
            }
            sb.AppendLine("            },");

            sb.AppendLine("        });");
        }

        sb.AppendLine("    }");
    }

    private static void EmitPropertyInfo(StringBuilder sb, PropertyModel prop, string declaringTypeName,
        List<SchemaModel> allSchemas) {
        var genericType = GetPropertyInfoGenericType(prop, allSchemas);
        var propName = NamingHelper.ToPascalCase(prop.Name);

        sb.AppendLine($"                JsonMetadataServices.CreatePropertyInfo<{genericType}>(options, new JsonPropertyInfoValues<{genericType}>");
        sb.AppendLine("                {");
        sb.AppendLine("                    IsProperty = true,");
        sb.AppendLine("                    IsPublic = true,");
        sb.AppendLine($"                    DeclaringType = typeof({declaringTypeName}),");
        sb.AppendLine($"                    PropertyName = \"{prop.Name}\",");
        sb.AppendLine($"                    Getter = static obj => (({declaringTypeName})obj).{propName},");
        sb.AppendLine("                    Setter = null,");
        sb.AppendLine("                }),");
    }

    private static void EmitParameterInfo(StringBuilder sb, PropertyModel prop, int position,
        List<SchemaModel> allSchemas) {
        var paramType = GetPropertyInfoGenericType(prop, allSchemas);
        var propName = NamingHelper.ToPascalCase(prop.Name);

        var baseType = TypeMapper.MapPropertyToCSharpType(prop);
        var isValueType = IsValueType(baseType, prop, allSchemas);
        var defaultValue = isValueType && prop.IsRequired ? $"default({paramType})" : "null";

        sb.AppendLine("                new()");
        sb.AppendLine("                {");
        sb.AppendLine($"                    Name = \"{prop.Name}\",");
        sb.AppendLine($"                    ParameterType = typeof({paramType}),");
        sb.AppendLine($"                    Position = {position},");
        sb.AppendLine($"                    HasDefaultValue = {(prop.IsRequired ? "false" : "true")},");
        sb.AppendLine($"                    DefaultValue = {defaultValue},");
        sb.AppendLine("                },");
    }

    private static void EmitEnumTypeInfo(StringBuilder sb, SchemaModel schema) {
        var typeName = NamingHelper.ToPascalCase(schema.Name);

        sb.AppendLine();
        sb.AppendLine($"    private static JsonTypeInfo<{typeName}> Create{typeName}TypeInfo(JsonSerializerOptions options)");
        sb.AppendLine("    {");
        sb.AppendLine($"        return JsonMetadataServices.CreateValueInfo<{typeName}>(options, JsonMetadataServices.GetEnumConverter<{typeName}>(options));");
        sb.AppendLine("    }");
    }

    /// <summary>
    /// Returns the full C# type including nullable suffix for optional properties.
    /// Used for constructor cast expressions.
    /// </summary>
    private static string GetFullCSharpType(PropertyModel prop, List<SchemaModel> allSchemas) {
        var baseType = TypeMapper.MapPropertyToCSharpType(prop);
        if (!prop.IsRequired) {
            return baseType + "?";
        }
        return baseType;
    }

    /// <summary>
    /// Returns the C# type for CreatePropertyInfo&lt;T&gt; and typeof() expressions.
    /// Reference types: always non-nullable (string, not string?).
    /// Value types: nullable if optional (int? for optional int).
    /// </summary>
    private static string GetPropertyInfoGenericType(PropertyModel prop, List<SchemaModel> allSchemas) {
        var baseType = TypeMapper.MapPropertyToCSharpType(prop);
        if (!prop.IsRequired && IsValueType(baseType, prop, allSchemas)) {
            return baseType + "?";
        }
        return baseType;
    }

    private static void EmitCollectionTypeEntries(StringBuilder sb, List<SchemaModel> schemas) {
        var listTypes = new HashSet<string>();
        var dictTypes = new HashSet<string>();

        foreach (var schema in schemas) {
            if (schema.Properties == null) continue;
            foreach (var prop in schema.Properties) {
                if (prop.IsArray) {
                    listTypes.Add(GetArrayElementType(prop));
                }
                if (prop.IsDictionary) {
                    dictTypes.Add(GetDictionaryValueType(prop));
                }
            }
        }

        if (listTypes.Count == 0 && dictTypes.Count == 0) return;

        sb.AppendLine();
        sb.AppendLine("        // Collection types");
        foreach (var elementType in listTypes) {
            sb.AppendLine($"        if (type == typeof(List<{elementType}>)) return JsonMetadataServices.CreateListInfo<List<{elementType}>, {elementType}>(options, new JsonCollectionInfoValues<List<{elementType}>> {{ ObjectCreator = static () => new List<{elementType}>() }});");
        }
        foreach (var valueType in dictTypes) {
            sb.AppendLine($"        if (type == typeof(Dictionary<string, {valueType}>)) return JsonMetadataServices.CreateDictionaryInfo<Dictionary<string, {valueType}>, string, {valueType}>(options, new JsonCollectionInfoValues<Dictionary<string, {valueType}>> {{ ObjectCreator = static () => new Dictionary<string, {valueType}>() }});");
        }
    }

    private static string GetArrayElementType(PropertyModel prop) {
        if (prop.ArrayItemsRef != null) {
            return NamingHelper.ToPascalCase(TypeMapper.GetRefName(prop.ArrayItemsRef));
        }
        return TypeMapper.MapToCSharpType(prop.ArrayItemsType, prop.ArrayItemsFormat);
    }

    private static string GetDictionaryValueType(PropertyModel prop) {
        if (prop.DictionaryValueRef != null) {
            return NamingHelper.ToPascalCase(TypeMapper.GetRefName(prop.DictionaryValueRef));
        }
        return TypeMapper.MapToCSharpType(prop.DictionaryValueType, null);
    }

    private static bool IsValueType(string csType, PropertyModel prop, List<SchemaModel> allSchemas) {
        switch (csType) {
            case "int":
            case "uint":
            case "long":
            case "float":
            case "double":
            case "bool":
            case "DateTime":
            case "DateOnly":
            case "JsonElement":
                return true;
        }

        // Check if it's an enum reference
        if (prop.Ref != null) {
            var refName = TypeMapper.GetRefName(prop.Ref);
            var refSchema = allSchemas.FirstOrDefault(s =>
                string.Equals(s.Name, refName, StringComparison.OrdinalIgnoreCase) ||
                string.Equals(NamingHelper.ToPascalCase(s.Name), NamingHelper.ToPascalCase(refName),
                    StringComparison.OrdinalIgnoreCase));
            if (refSchema != null && refSchema.Kind == SchemaKind.Enum) {
                return true;
            }
        }

        return false;
    }
}
