using Hardened.OpenApi.SourceGenerator.Models;

namespace Hardened.OpenApi.SourceGenerator.Emitters;

internal static class RecordEmitter {
    public static string Emit(SchemaModel schema, string ns) {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // Collect required usings based on property types
        var usings = new HashSet<string>();
        foreach (var prop in schema.Properties) {
            var csType = TypeMapper.MapPropertyToCSharpType(prop);
            if (csType.Contains("JsonElement")) usings.Add("using System.Text.Json;");
            if (csType.StartsWith("List<")) usings.Add("using System.Collections.Generic;");
            if (csType.StartsWith("Dictionary<")) usings.Add("using System.Collections.Generic;");
        }
        foreach (var u in usings.OrderBy(u => u)) {
            sb.AppendLine(u);
        }
        if (usings.Count > 0) sb.AppendLine();

        sb.AppendLine($"namespace {ns}.Models;");
        sb.AppendLine();

        var recordName = NamingHelper.ToPascalCase(schema.Name);

        if (schema.Properties.Count == 0) {
            sb.AppendLine($"public record {recordName};");
            return sb.ToString();
        }

        sb.Append($"public record {recordName}(");
        sb.AppendLine();

        // Required parameters must precede optional ones in C# record constructors.
        var sorted = schema.Properties.OrderByDescending(p => p.IsRequired).ToList();

        for (var i = 0; i < sorted.Count; i++) {
            var prop = sorted[i];
            var csType = TypeMapper.MapPropertyToCSharpType(prop);
            var propName = NamingHelper.ToPascalCase(prop.Name);
            var nullable = !prop.IsRequired ? "?" : "";

            sb.Append($"    {csType}{nullable} {propName}");

            if (!prop.IsRequired) {
                sb.Append(" = default");
            }

            if (i < sorted.Count - 1) {
                sb.AppendLine(",");
            } else {
                sb.Append(")");
            }
        }

        sb.AppendLine(";");
        return sb.ToString();
    }
}
