using Hardened.OpenApi.SourceGenerator.Models;

namespace Hardened.OpenApi.SourceGenerator.Emitters;

internal static class ServiceInterfaceEmitter {
    public static string Emit(ServiceModel service, string ns) {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"using {ns}.Models;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns}.Services;");
        sb.AppendLine();

        var interfaceName = NamingHelper.ToInterfaceName(service.Tag);

        sb.AppendLine($"public interface {interfaceName}");
        sb.AppendLine("{");

        foreach (var op in service.Operations) {
            var methodName = NamingHelper.ToMethodName(op.OperationId);
            var returnType = GetReturnType(op, ns);
            var parameters = GetParameterList(op, ns);

            sb.AppendLine($"    /// <summary>{op.HttpMethod} {op.Path} &rarr; {op.SuccessStatusCode}</summary>");
            sb.AppendLine($"    {returnType} {methodName}({parameters});");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    internal static string GetReturnType(OperationModel op, string ns) {
        if (op.ResponseRef != null) {
            var typeName = NamingHelper.ToPascalCase(TypeMapper.GetRefName(op.ResponseRef));
            return $"Task<{typeName}>";
        }

        if (op.ResponseIsArray && op.ResponseArrayItemsRef != null) {
            var itemType = NamingHelper.ToPascalCase(TypeMapper.GetRefName(op.ResponseArrayItemsRef));
            return $"Task<List<{itemType}>>";
        }

        if (op.ResponseType != null) {
            var csType = TypeMapper.MapToCSharpType(op.ResponseType, op.ResponseFormat);
            if (csType != "object") {
                return $"Task<{csType}>";
            }
        }

        return "Task";
    }

    internal static string GetParameterList(OperationModel op, string ns) {
        var parts = new List<string>();

        foreach (var param in op.Parameters) {
            if (param.In == "path" || param.In == "query") {
                var csType = TypeMapper.MapParameterToCSharpType(param);
                var nullable = !param.IsRequired ? "?" : "";
                var name = NamingHelper.ToParameterName(param.Name);
                parts.Add($"{csType}{nullable} {name}");
            }
        }

        if (op.RequestBodyRef != null) {
            var bodyType = NamingHelper.ToPascalCase(TypeMapper.GetRefName(op.RequestBodyRef));
            parts.Add($"{bodyType} body");
        } else if (op.RequestBodyType != null) {
            var bodyType = TypeMapper.MapToCSharpType(op.RequestBodyType, null);
            parts.Add($"{bodyType} body");
        }

        return string.Join(", ", parts);
    }
}
