using System.Text;
using Hardened.OpenApi.SourceGenerator.Models;

namespace Hardened.OpenApi.SourceGenerator.Emitters;

internal static class ValidationFilterEmitter {
    public static string? Emit(OperationModel operation, string ns, string modelsNamespace, bool excludeFromCoverage = false) {
        if (!operation.HasValidationConstraints) return null;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Hardened.Requests.Abstract.Execution;");
        sb.AppendLine("using Hardened.Requests.Abstract.RequestFilter;");
        sb.AppendLine("using Hardened.Requests.Abstract.Validation;");
        sb.AppendLine("using Hardened.Requests.Runtime.Validation;");
        sb.AppendLine("using Hardened.Requests.Runtime.Validation.Rules;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();

        var className = NamingHelper.ToPascalCase(operation.OperationId) + "_ValidationFilterProvider";

        if (excludeFromCoverage) {
            sb.AppendLine("[System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        }
        sb.AppendLine($"public class {className} : IRequestFilterProvider {{");
        sb.AppendLine("    public IEnumerable<RequestFilterInfo> GetFilters(IExecutionRequestHandlerInfo handlerInfo) {");
        sb.AppendLine("        yield return new RequestFilterInfo(");
        sb.AppendLine("            ctx => new ValidationFilter(");

        // Parameter rules
        EmitParameterRules(sb, operation);

        // Body property rules
        EmitBodyPropertyRules(sb, operation, modelsNamespace);

        sb.AppendLine("            ),");
        sb.AppendLine("            FilterOrder.Validation);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitParameterRules(StringBuilder sb, OperationModel operation) {
        var paramRules = new List<ParameterModel>();
        foreach (var p in operation.Parameters) {
            if (p.HasValidationConstraints) paramRules.Add(p);
        }

        sb.Append("                parameterRules: new ParameterValidationInfo[] {");

        if (paramRules.Count == 0) {
            sb.AppendLine(" },");
            return;
        }

        sb.AppendLine();

        for (var i = 0; i < paramRules.Count; i++) {
            var param = paramRules[i];
            var ruleModel = ValidationRuleModel.FromParameter(param);
            var paramName = NamingHelper.ToParameterName(param.Name);

            sb.Append($"                    new ParameterValidationInfo(\"{paramName}\", ");
            EmitRuleArray(sb, ruleModel);
            sb.Append(")");

            if (i < paramRules.Count - 1) {
                sb.AppendLine(",");
            } else {
                sb.AppendLine();
            }
        }

        sb.AppendLine("                },");
    }

    private static void EmitBodyPropertyRules(StringBuilder sb, OperationModel operation,
        string modelsNamespace) {
        var bodyProps = new List<PropertyModel>();
        foreach (var p in operation.RequestBodyProperties) {
            if (p.HasValidationConstraints) bodyProps.Add(p);
        }

        if (bodyProps.Count == 0 && operation.RequestBodyRef == null) {
            // No body validation needed - pass null/defaults
            sb.Append("                bodyPropertyRules: null");
            return;
        }

        if (bodyProps.Count == 0) {
            sb.AppendLine("                bodyPropertyRules: null,");
            sb.AppendLine("                bodyParameterName: \"body\",");

            var bodyTypeName = GetBodyTypeName(operation, modelsNamespace);
            sb.Append($"                requestBodyType: typeof({bodyTypeName})");
            return;
        }

        var bodyType = GetBodyTypeName(operation, modelsNamespace);

        sb.AppendLine("                bodyPropertyRules: new PropertyValidationInfo[] {");

        for (var i = 0; i < bodyProps.Count; i++) {
            var prop = bodyProps[i];
            var ruleModel = ValidationRuleModel.FromProperty(prop);
            var propName = prop.Name;
            var csPropName = NamingHelper.ToPascalCase(prop.Name);

            sb.Append($"                    new PropertyValidationInfo(\"{propName}\", ");
            EmitRuleArray(sb, ruleModel);
            sb.Append($", body => (({bodyType})body).{csPropName})");

            if (i < bodyProps.Count - 1) {
                sb.AppendLine(",");
            } else {
                sb.AppendLine();
            }
        }

        sb.AppendLine("                },");
        sb.AppendLine("                bodyParameterName: \"body\",");
        sb.Append($"                requestBodyType: typeof({bodyType})");
    }

    private static string GetBodyTypeName(OperationModel operation, string modelsNamespace) {
        if (operation.RequestBodyRef != null) {
            return modelsNamespace + "." +
                   NamingHelper.ToPascalCase(TypeMapper.GetRefName(operation.RequestBodyRef));
        }

        return "object";
    }

    private static void EmitRuleArray(StringBuilder sb, ValidationRuleModel model) {
        var rules = new List<string>();

        if (model.IsRequired) {
            rules.Add("RequiredRule.Instance");
        }

        if (model.MinLength.HasValue || model.MaxLength.HasValue) {
            var min = model.MinLength.HasValue ? model.MinLength.Value.ToString() : "null";
            var max = model.MaxLength.HasValue ? model.MaxLength.Value.ToString() : "null";
            rules.Add($"new StringLengthRule({min}, {max})");
        }

        if (model.Minimum.HasValue || model.Maximum.HasValue) {
            var min = model.Minimum.HasValue ? model.Minimum.Value.ToString() + "m" : "null";
            var max = model.Maximum.HasValue ? model.Maximum.Value.ToString() + "m" : "null";
            var exMin = model.ExclusiveMinimum ? "true" : "false";
            var exMax = model.ExclusiveMaximum ? "true" : "false";
            rules.Add($"new RangeRule({min}, {max}, {exMin}, {exMax})");
        }

        if (model.Pattern != null) {
            var escaped = model.Pattern.Replace("\\", "\\\\").Replace("\"", "\\\"");
            rules.Add($"new PatternRule(\"{escaped}\")");
        }

        if (model.EnumValues is { Count: > 0 }) {
            var values = string.Join(", ", model.EnumValues.Select(v => $"\"{v}\""));
            rules.Add($"new EnumRule(new string[] {{ {values} }})");
        }

        if (model.MinItems.HasValue || model.MaxItems.HasValue) {
            var min = model.MinItems.HasValue ? model.MinItems.Value.ToString() : "null";
            var max = model.MaxItems.HasValue ? model.MaxItems.Value.ToString() : "null";
            rules.Add($"new ArrayBoundsRule({min}, {max})");
        }

        sb.Append("new IValidationRule[] { ");
        sb.Append(string.Join(", ", rules));
        sb.Append(" }");
    }
}
