// <auto-generated/>
#nullable enable
#pragma warning disable CS1591 // generated members carry no doc comments
using Hardened.Requests.Abstract.Links;
using TestApp;

namespace TestApp
{
    public partial class Application
    {

        /// <summary>
        /// The routes Application declares, as paths. For a link a client can call, use Application.Links.
        /// </summary>
        public static class Routes
        {

            public static class Home
            {

                public static string Hello()
                {
                    return "/hello";
                }
            }
        }

        /// <summary>
        /// Links to Application's routes, as a client would call them. Resolve from the container, or read it off a template.
        /// </summary>
        public sealed class Links
        {
            private readonly global::Hardened.Requests.Abstract.Links.ILinkContext _context;
            private global::TestApp.Application.Links.HomeLinks? _Home;

            public Links(global::Hardened.Requests.Abstract.Links.ILinkContext context)
            {
                _context = context;
            }

            public global::TestApp.Application.Links.HomeLinks Home => _Home ??= new HomeLinks(_context);

            public sealed class HomeLinks
            {
                private readonly global::Hardened.Requests.Abstract.Links.ILinkContext _context;

                public HomeLinks(global::Hardened.Requests.Abstract.Links.ILinkContext context)
                {
                    _context = context;
                }

                public string Hello()
                {
                    return _context.Resolve(global::TestApp.Application.Routes.Home.Hello());
                }

                public string HelloAbsolute()
                {
                    return _context.Absolute(global::TestApp.Application.Routes.Home.Hello());
                }
            }
        }
    }
}
