// <auto-generated/>
#nullable enable
#pragma warning disable CS1591 // generated members carry no doc comments
namespace TestApp.Generated
{
    public partial class HomeController_Hello : global::Hardened.Requests.Runtime.Execution.BaseExecutionHandler<global::TestApp.HomeController>
    {
        private static readonly global::Hardened.Requests.Runtime.Execution.ExecutionRequestHandlerInfo _handlerInfo =         new global::Hardened.Requests.Runtime.Execution.ExecutionRequestHandlerInfo("/hello", "GET", typeof(global::TestApp.HomeController), "Hello")
;

        public HomeController_Hello(global::System.IServiceProvider serviceProvider, string? routePath = null)
            : base(global::Hardened.Requests.Runtime.Execution.ExecutionHelper.StandardFilterEmptyParameters<global::TestApp.HomeController>(
            serviceProvider,
            _handlerInfo.WithPath(routePath),
            InvokeMethod,
            global::Hardened.Requests.Runtime.Execution.ExecutionHelper.GetFilterInfo()
        ), null)
        {
        }

        private static void InvokeMethod(global::Hardened.Requests.Abstract.Execution.IExecutionContext context, global::TestApp.HomeController controller)
        {
            context.Response.ResponseValue = controller.Hello();
        }
    }
}
