<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="xunit.v3" Version="1.*" />
        <PackageReference Include="Microsoft.OpenApi.Readers" Version="1.6.22" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Hardened.OpenApi.SourceGenerator\Hardened.OpenApi.SourceGenerator.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Update="Fixtures\**\*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
