<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(HardenedTargetFramework)</TargetFramework>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="NSubstitute" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Hardened.Aws.DynamoDbClient\Hardened.Aws.DynamoDbClient.csproj" />
        <ProjectReference Include="..\Hardened.Aws.DynamoDbClient.Testing\Hardened.Aws.DynamoDbClient.Testing.csproj" />
    </ItemGroup>

</Project>
