<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>.net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>True</IsPackable>
        <PackageId>Hardened.Amz.Shared.Lambda.Testing</PackageId>
        <Authors>Ian Johnson</Authors>
        <PackageTags>Hardened.Framework</PackageTags>
        <PackageProjectUrl>https://github.com/ipjohnson/Hardened.Framework</PackageProjectUrl>
        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://github.com/ipjohnson/Hardened.Framework</RepositoryUrl>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Amazon.Lambda.Core" Version="2.2.0" />
        <PackageReference Include="Hardened.Requests.Runtime" Version="0.1.0-Alpha1139" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.1" />
        <PackageReference Include="Microsoft.Extensions.Primitives" Version="8.0.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.10.0" />
    </ItemGroup>

</Project>
