namespace Hardened.SourceGenerator.Shared;

/// <summary>
/// The header every generated file carries.
/// </summary>
/// <remarks>
/// <para>
/// <c>// &lt;auto-generated/&gt;</c> on the first line is what tells the compiler a file was not
/// written by hand. Without it, turning on <c>GenerateDocumentationFile</c> - which a consumer has
/// to do for their own doc comments to reach their published document - reports CS1591 for every
/// public member these generators emit. Measured on one integration application: 1,436 warnings,
/// 560 of them from a single generated links file, against an application whose own undocumented
/// members number a couple of dozen. The signal the flag exists to give is buried by output the
/// consumer did not write and cannot document.
/// </para>
/// <para>
/// The build task has always written it - <c>SpecFileEmitter</c> prepends exactly this - so the
/// specification-first path was quiet while the generators beside it were not.
/// </para>
/// </remarks>
public static class GeneratedSource {

    /// <summary>Prepends the header to a generated file's text.</summary>
    /// <remarks>
    /// The marker and the pragma both, because they are read by different things.
    /// <c>&lt;auto-generated/&gt;</c> is what an analyzer honours; CS1591 is a compiler warning and
    /// honours neither the marker nor the file name, so the only thing that quiets it in a file the
    /// consumer did not write is the pragma. Disabled rather than restored at the end of the file:
    /// there is nothing after the generated source, and a restore would only matter if something
    /// were appended to it.
    /// </remarks>
    /// <remarks>
    /// <c>#nullable enable</c> travels with the marker rather than being optional beside it. Once a
    /// file is recognised as generated, a nullable annotation in it is CS8669 unless the file says
    /// which context it is in - so adding the marker without the directive turns a quiet build into
    /// a broken one. <c>SpecFileEmitter</c> has always written both together.
    /// </remarks>
    public static string Header(string source) =>
        source.StartsWith(Marker, System.StringComparison.Ordinal)
            ? source
            : Marker +
              "\n#nullable enable" +
              "\n#pragma warning disable CS1591 // generated members carry no doc comments\n" +
              source;

    private const string Marker = "// <auto-generated/>";
}
