<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(HardenedTargetFramework)</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Hardened.IntegrationTests.CloudRunInvoke.SUT\Hardened.IntegrationTests.CloudRunInvoke.SUT.csproj"
                          ReferenceOutputAssembly="false"/>
        <ProjectReference Include="..\..\..\Hardened.Gcp.CloudRun.Testing.Containers\Hardened.Gcp.CloudRun.Testing.Containers.csproj"/>
    </ItemGroup>

</Project>
