using System.Linq;
using Hardened.Requests.Abstract.Attributes;
using Hardened.SourceGenerator.Web;
using Hardened.SourceGeneration.Testing;
using Hardened.Web.Runtime.Attributes;
using Xunit;

namespace Hardened.Web.SourceGenerator.Tests;

/// <summary>
/// What every file this generator writes carries, and what a doc comment reaches.
/// </summary>
/// <remarks>
/// <para>
/// Driven through the generator rather than by calling the helpers, because this assembly compiles
/// its own copy of the shared generator sources and a test over the other copy says nothing about
/// this one.
/// </para>
/// <para>
/// The prose those doc comments carry is asserted in <c>XmlDocumentationTests</c> and again on the
/// wire in the integration application. What is asserted here is the header, which is this
/// assembly's copy of it.
/// </para>
/// </remarks>
public class GeneratedFileHeaderTests {

    private static readonly System.Type[] Anchors = [
        typeof(GetAttribute),
        typeof(FromBodyAttribute)
    ];

    private const string Source = """
        using Hardened.Shared.Runtime.Attributes;
        using Hardened.Web.Runtime.Attributes;
        using Hardened.Web.Runtime.OpenApi;

        namespace TestApp;

        [WebLibrary]
        [Enable<OpenApiDocumentPublishing>]
        public partial class Application;

        /// <summary>Everything about a widget.</summary>
        public class Widget {
            /// <summary>The identifier the store assigned.</summary>
            public string Id { get; set; } = "";
        }

        public class WidgetController {
            /// <summary>Reads one widget.</summary>
            /// <remarks>Answers the widget, or nothing when the id names none.</remarks>
            /// <param name="id">Which widget to read.</param>
            [Get("/widgets/{id}")]
            public Widget Get(string id) => new();
        }
        """;

    private static GeneratorResult Generate() =>
        GeneratorTestHarness.Run(Source, new WebLibrarySourceGenerator(), Anchors);

    [Fact]
    public void EveryGeneratedFileOpensWithTheMarker() {
        foreach (var source in Generate().AssertNoErrors().GeneratedSources) {
            Assert.StartsWith("// <auto-generated/>", source.Value, System.StringComparison.Ordinal);
        }
    }

    /// <summary>
    /// And the two directives that travel with it.
    /// </summary>
    /// <remarks>
    /// CS1591 is a compiler warning and honours neither the marker nor the file name, so the pragma
    /// is the only thing that quiets it for members a consumer did not write. The nullable context
    /// is required because a file recognised as generated needs one declared, or its annotations
    /// are CS8669.
    /// </remarks>
    [Fact]
    public void EveryGeneratedFileDeclaresItsContextAndQuietsTheDocWarning() {
        foreach (var source in Generate().AssertNoErrors().GeneratedSources) {
            Assert.Contains("#nullable enable", source.Value);
            Assert.Contains("#pragma warning disable CS1591", source.Value);
        }
    }


}
