using System.Text;
using Hardened.Web.StaticContent.BuildTask;

namespace Hardened.Web.StaticContent.BuildTask.Tests;

/// <summary>
/// The C# a scan becomes.
///
/// <para>
/// This is emitted into somebody else's assembly and compiled there, so a mistake in it is a build
/// error in a project that has done nothing wrong - and the error points at generated code the
/// author never wrote. The shape is asserted rather than the exact text, except where the exact
/// text is the point: a path with a quote in it, bytes that have to stay bytes.
/// </para>
/// </summary>
public class ManifestEmitterTests : IDisposable {

    private readonly string _root;

    public ManifestEmitterTests() {
        _root = Path.Combine(Path.GetTempPath(), "hardened-emit-" + Guid.NewGuid().ToString("N"));

        Directory.CreateDirectory(_root);
    }

    public void Dispose() {
        try { Directory.Delete(_root, true); } catch { /* best effort */ }

        GC.SuppressFinalize(this);
    }

    private void Write(string relative, string content) {
        var path = Path.Combine(_root, relative);

        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, content);
    }

    private string Emit(string? fallBack = null, long embed = 1024 * 1024,
        string namespaceName = "Contoso.Orders") =>
        ManifestEmitter.Emit(
            StaticContentScan.Scan(_root, "/", fallBack, embed), namespaceName, true);

    #region shape

    [Fact]
    public void TheManifestIsAGeneratedRegisteredImplementation() {
        Write("app.js", "console.log('hi');");

        var source = Emit();

        Assert.Contains("// <auto-generated/>", source);
        Assert.Contains("namespace Contoso.Orders;", source);
        Assert.Contains("[SingletonService(Using = RegistrationType.Try)]", source);
        Assert.Contains(
            "public sealed class GeneratedStaticContentManifest : IStaticContentManifest {", source);
    }

    /// <summary>
    /// Generated code is kept out of the coverage numbers, because it is not the kind of code a
    /// test can meaningfully cover and its size swamps everything the assembly actually wrote.
    /// </summary>
    [Fact]
    public void CoverageExclusionIsOptional() {
        Write("app.js", "x");

        Assert.Contains("ExcludeFromCodeCoverage", Emit());

        Assert.DoesNotContain(
            "ExcludeFromCodeCoverage",
            ManifestEmitter.Emit(StaticContentScan.Scan(_root, "/", null, 1024), "N", false));
    }

    [Fact]
    public void EveryFileBecomesAnEntry() {
        Write("app.js", "console.log('hi');");
        Write(Path.Combine("css", "site.css"), "body{}");

        var source = Emit();

        Assert.Contains("\"/app.js\"", source);
        Assert.Contains("\"/css/site.css\"", source);
    }

    [Fact]
    public void TheFallBackRouteIsCarried() {
        Write("index.html", "<html/>");

        Assert.Contains("FallBackRoute => \"/index.html\"", Emit(fallBack: "index.html"));
        Assert.Contains("FallBackRoute => null", Emit());
    }

    #endregion

    #region the bytes

    /// <summary>
    /// Bytes go out as a <c>byte[]</c> initializer, which the compiler lowers into a metadata blob.
    /// As a string literal they would live in the <c>#US</c> heap as UTF-16 and cost two bytes per
    /// ASCII character; base64 gives back a third of what compression saved.
    /// </summary>
    [Fact]
    public void EmbeddedContentIsAByteArrayAndNotAString() {
        Write("app.js", "hi");

        var source = Emit();

        Assert.Contains("private static readonly byte[] ", source);

        // "hi" as bytes, not as text.
        Assert.Contains("104,105", source.Replace("\n", "").Replace(" ", ""));
        Assert.DoesNotContain("\"hi\"", source);
    }

    /// <summary>
    /// An alias shares its target's field rather than emitting the bytes twice. A shell aliased at
    /// both <c>/</c> and <c>/index.html</c> would otherwise ship three copies of itself.
    /// </summary>
    [Fact]
    public void AnAliasDoesNotDuplicateTheBytes() {
        Write("index.html", new string('x', 200));

        var source = Emit();

        var fields = source.Split("private static readonly byte[] ").Length - 1;

        // One for the content, one for its compressed form. Not six, which is what three routes
        // pointing at one file would cost if each carried its own.
        Assert.True(fields <= 2, $"expected at most 2 byte arrays, found {fields}");
    }

    [Fact]
    public void ContentOverTheThresholdIsReferencedByPathRatherThanEmbedded() {
        Write("big.bin", new string('a', 5000));

        var source = Emit(embed: 1024);

        Assert.DoesNotContain("private static readonly byte[] ", source);
        Assert.Contains("\"big.bin\"", source);
    }

    #endregion

    #region things that would not compile

    /// <summary>
    /// A path with a character that means something in C# has to survive being written into it. A
    /// quote in a file name is legal on every platform this runs on and would otherwise close the
    /// literal and produce a syntax error in somebody else's project.
    /// </summary>
    [Fact]
    public void APathNeedingEscapingIsEscaped() {
        var awkward = "it's \"quoted\" \\ odd.txt";

        try {
            Write(awkward, "content");
        }
        catch (Exception exception) when (exception is IOException or ArgumentException) {
            return; // The file system will not take the name; nothing to assert.
        }

        var source = Emit();

        Assert.Contains("\\\"quoted\\\"", source);
        Assert.Contains("\\\\", source);
    }

    /// <summary>
    /// Two files whose readable names collide after truncation still get distinct fields. The
    /// readable part is a convenience; the hash suffix is what actually keeps them apart.
    /// </summary>
    [Fact]
    public void TwoSimilarlyNamedFilesGetDistinctFields() {
        Write(Path.Combine("a-very-long-directory-name-that-truncates", "one.txt"), "1");
        Write(Path.Combine("a-very-long-directory-name-that-truncates", "two.txt"), "2");

        var source = Emit();

        var names = source.Split("private static readonly byte[] ")
            .Skip(1)
            .Select(part => part.Split(' ')[0])
            .ToList();

        Assert.Equal(names.Count, names.Distinct().Count());
    }

    /// <summary>
    /// An empty directory still emits something that compiles. A manifest with no entries is an
    /// application that declared a content directory and shipped nothing in it, which is a warning
    /// rather than a reason to emit a file with a dangling array.
    /// </summary>
    [Fact]
    public void AnEmptyScanStillEmitsAValidClass() {
        var source = Emit();

        Assert.Contains("private static readonly StaticContentManifestEntry[] _entries = {", source);
        Assert.Contains("};", source);
        Assert.Contains("FallBackRoute => null", source);
    }

    #endregion

    #region determinism

    /// <summary>
    /// Two emissions of one tree are byte-identical. Anything else makes every build a rebuild,
    /// because the file is an input to the compilation.
    /// </summary>
    [Fact]
    public void TwoEmissionsOfOneTreeAreIdentical() {
        Write("app.js", "console.log('hi');");
        Write(Path.Combine("css", "site.css"), new string('a', 3000));
        Write("index.html", "<html/>");

        Assert.Equal(Emit(fallBack: "index.html"), Emit(fallBack: "index.html"));
    }

    #endregion
}
