using System.Collections.Generic;
using System.Linq;
using CSharpAuthor;
using Hardened.OpenApi.BuildTask.Validation;
using Hardened.OpenApi.SourceGenerator.Models;

namespace Hardened.OpenApi.SourceGenerator.Emitters;

/// <summary>
/// Composes one spec's generated C# into a single file.
/// </summary>
/// <remarks>
/// <para>
/// This owns everything about the file: which namespaces exist, what goes in them, and which types
/// carry <c>[ExcludeFromCodeCoverage]</c>. The individual emitters own one type each and know none
/// of it - they are handed a container and add to it.
/// </para>
/// <para>
/// The emitters used to return whole files, because a source generator addresses its output by hint
/// name and every call produced one. A build task writes files itself, so that shape bought nothing
/// and cost a duplicated header, a hand-written <c>using</c> block and a namespace line in each of
/// them.
/// </para>
/// </remarks>
internal static class SpecFileEmitter {

    /// <summary>Types under the root namespace that models live in.</summary>
    private const string ModelsNamespace = "Models";

    /// <summary>Types under the root namespace that service interfaces live in.</summary>
    private const string ServicesNamespace = "Services";

    public static string Emit(OpenApiSpecModel model, string rootNamespace, bool excludeFromCoverage) {
        // An unnamed namespace writes no wrapper of its own, so this is the file rather than a
        // namespace in it. Filter types declare their own namespace in the spec and may sit outside
        // the root entirely, which is why the file needs to hold more than one top-level block.
        var file = new CSharpFileDefinition();

        var root = new NamespaceDefinition(rootNamespace);
        file.AddComponent(root);

        var models = root.AddNamespace(ModelsNamespace);
        var modelsNamespace = rootNamespace + "." + ModelsNamespace;

        foreach (var schema in model.Schemas) {
            Coverage.Apply(SchemaEmitter.Emit(models, schema, modelsNamespace), excludeFromCoverage);
        }

        if (model.Services.Count > 0) {
            var services = root.AddNamespace(ServicesNamespace);

            foreach (var service in model.Services) {
                Coverage.Apply(
                    ServiceInterfaceEmitter.Emit(services, service, modelsNamespace),
                    excludeFromCoverage);
            }
        }

        Coverage.Apply(
            JsonTypeInfoEmitter.Emit(models, model.Schemas, modelsNamespace, model.FileName),
            excludeFromCoverage);

        EmitFilterTypes(file, model, excludeFromCoverage);

        var context = new OutputContext();

        file.WriteOutput(context);

        var validation = ValidationEmitter.Emit(model, rootNamespace);

        return "// <auto-generated/>\n#nullable enable\n\n" +
            MergeUsings(context.Output(), validation.Usings) + validation.Body;
    }

    /// <summary>
    /// Puts the validation half's usings into the block at the top of the file.
    /// </summary>
    /// <remarks>
    /// A using directive must precede every type in the file, and the validators are appended after
    /// the models - so leaving theirs where they were written is CS1529. Duplicates are dropped
    /// rather than repeated, since a repeated directive is CS0105 and CI treats that as an error.
    /// </remarks>
    private static string MergeUsings(string emitted, IReadOnlyList<string> usings) {
        if (usings.Count == 0) {
            return emitted;
        }

        var lines = emitted.Split('\n').ToList();
        var insertAt = 0;
        var existing = new HashSet<string>(System.StringComparer.Ordinal);

        for (var i = 0; i < lines.Count; i++) {
            var line = lines[i].Trim();

            if (line.StartsWith("using ", System.StringComparison.Ordinal)) {
                existing.Add(line);
                insertAt = i + 1;
            } else if (line.Length != 0) {
                break;
            }
        }

        lines.InsertRange(insertAt, usings.Where(u => !existing.Contains(u)));

        return string.Join("\n", lines);
    }

    /// <summary>
    /// Filter attributes, each in the namespace its spec declared.
    /// </summary>
    /// <remarks>
    /// Those namespaces are whatever the author wrote in <c>x-filter-types</c> and need not sit under
    /// the root, so each becomes a top-level block rather than being nested. Two filter types
    /// sharing a namespace share the block - which is what
    /// <see cref="NamespaceDefinition.AddNamespace"/> does within a namespace, and what this does at
    /// file level, where there is nothing to ask.
    /// </remarks>
    private static void EmitFilterTypes(
        CSharpFileDefinition file, OpenApiSpecModel model, bool excludeFromCoverage) {
        var namespaces = new Dictionary<string, NamespaceDefinition>(System.StringComparer.Ordinal);

        foreach (var filterType in model.FilterTypes) {
            if (!filterType.Generate) {
                continue;
            }

            if (!namespaces.TryGetValue(filterType.Namespace, out var filterNamespace)) {
                filterNamespace = new NamespaceDefinition(filterType.Namespace);
                namespaces.Add(filterType.Namespace, filterNamespace);
                file.AddComponent(filterNamespace);
            }

            Coverage.Apply(FilterTypeEmitter.Emit(filterNamespace, filterType), excludeFromCoverage);
        }
    }
}
