using System.Net.Http.Json;
using Hardened.IntegrationTests.WebApp.SUT.Client;
using Hardened.IntegrationTests.WebApp.SUT.Models;
using Microsoft.Kiota.Abstractions.Authentication;
using Microsoft.Kiota.Http.HttpClientLibrary;

namespace Hardened.IntegrationTests.WebApp.SUT.Tests.Transport;

/// <summary>
/// The shape an NSwag generator or a hand writes: one constructor over an <see cref="HttpClient"/>.
/// Built by convention, with no factory.
/// </summary>
public sealed class ProbeClient {
    public ProbeClient(HttpClient http) {
        Http = http;
    }

    public HttpClient Http { get; }

    public Task<HttpResponseMessage> Pets(CancellationToken cancellationToken) =>
        Http.GetAsync("authorization/pets", cancellationToken);

    public async Task<int> Add(MathAddModel model, CancellationToken cancellationToken) {
        using var response = await Http.PostAsJsonAsync("int/add", model, cancellationToken);

        response.EnsureSuccessStatusCode();

        return await response.Content.ReadFromJsonAsync<int>(cancellationToken);
    }
}

/// <summary>
/// The shape Kiota writes: the constructor takes an adapter the harness has never heard of, so
/// the test project says how to build one, once.
/// </summary>
public sealed class AdaptedClient {
    public AdaptedClient(Func<Uri, HttpClient> adapter) {
        Http = adapter(new Uri("http://harness"));
    }

    public HttpClient Http { get; }

    public Task<HttpResponseMessage> Pets(CancellationToken cancellationToken) =>
        Http.GetAsync("authorization/pets", cancellationToken);
}

public sealed class AdaptedClientFactory : ITestClientFactory<AdaptedClient> {
    public AdaptedClient Create(HttpClient http) => new(_ => http);
}

/// <summary>Neither route: nothing the harness can build it from.</summary>
public sealed class OrphanClient {
    public OrphanClient(string endpoint) {
        Endpoint = endpoint;
    }

    public string Endpoint { get; }
}

/// <summary>
/// How a test builds the generated client over the pipeline, once: the shape the hardened-web
/// template scaffolds into its own TestClients.cs. <see cref="WebAppClient"/> is Kiota's output,
/// generated by Hardened.IntegrationTests.WebApp.SUT.Client from the exported document.
/// </summary>
/// <remarks>
/// A plain HttpClient rather than KiotaClientFactory.Create, which would wrap the handler in Kiota's
/// retry and redirect middleware: a test of a 429 or a 308 wants what the pipeline answered, not
/// what the middleware made of it. The base URL is required by Kiota and ignored by the handler;
/// the document has no servers entry. Credentials are already on the HttpClient.
/// </remarks>
public sealed class WebAppClientFactory : ITestClientFactory<WebAppClient> {
    public WebAppClient Create(HttpClient http) =>
        new(new HttpClientRequestAdapter(new AnonymousAuthenticationProvider(), httpClient: http) {
            BaseUrl = "http://harness"
        });
}
