namespace Hardened.IntegrationTests.Smithy.SUT.Tests;

/// <summary>
/// A Smithy-described service, served.
/// </summary>
/// <remarks>
/// The parser tests assert what the reader produces and the task tests assert what reaches disk.
/// These assert the only thing that actually matters to someone using this: that a request arrives
/// at the right handler with its parameters bound, its constraints enforced and its response
/// serialised - through routing, binding, validation and JSON that were all generated by code with
/// no knowledge of Smithy.
/// </remarks>
public class PetStoreRoutingTests {

    [HardenedTest]
    public async Task GetPet_BindsThePathLabel(ITestWebApp app) {
        var response = await app.Get("/pets/1");

        response.Assert.Ok();

        var output = response.Deserialize<GetPetOutput>();

        Assert.NotNull(output);
        Assert.Equal("1", output.Pet.Id);
        Assert.Equal("Buddy", output.Pet.Name);
    }

    /// <summary>
    /// The member is called <c>detailed</c> in the model and binds under <c>verbose</c>, which is
    /// what <c>@httpQuery("verbose")</c> says. The wire name is the contract.
    /// </summary>
    [HardenedTest]
    public async Task GetPet_BindsTheQueryParameterUnderItsWireName(ITestWebApp app) {
        var withNickname = await app.Get("/pets/2?verbose=true");
        var withoutNickname = await app.Get("/pets/2?verbose=false");

        withNickname.Assert.Ok();
        withoutNickname.Assert.Ok();

        Assert.Equal("Lu", withNickname.Deserialize<GetPetOutput>()!.Pet.Nickname);
        Assert.Null(withoutNickname.Deserialize<GetPetOutput>()!.Pet.Nickname);
    }

    /// <summary>
    /// <c>@pattern</c> on the label reached the generated validator as a <c>[GeneratedRegex]</c>,
    /// which a source generator cannot emit for itself - it works because the build task writes the
    /// file before the compiler runs.
    /// </summary>
    [HardenedTest]
    public async Task GetPet_RejectsAPathLabelFailingThePattern(ITestWebApp app) {
        var response = await app.Get("/pets/NOT_VALID");

        response.Assert.BadRequest();
    }

    [HardenedTest]
    public async Task ListPets_ReturnsTheCollection(ITestWebApp app) {
        var response = await app.Get("/pets");

        response.Assert.Ok();

        var output = response.Deserialize<ListPetsOutput>();

        Assert.NotNull(output);
        Assert.Equal(2, output.Pets.Count);
    }

    [HardenedTest]
    public async Task ListPets_BindsTheQueryParameter(ITestWebApp app) {
        var response = await app.Get("/pets?limit=1");

        response.Assert.Ok();
        Assert.Single(response.Deserialize<ListPetsOutput>()!.Pets);
    }

    /// <summary>@range(min: 1, max: 100) on the query member.</summary>
    [HardenedTest]
    public async Task ListPets_RejectsALimitOutsideTheDeclaredRange(ITestWebApp app) {
        var response = await app.Get("/pets?limit=500");

        response.Assert.BadRequest();
    }

    /// <summary>
    /// Every member of the input structure carries no binding trait, so the whole structure is the
    /// JSON body - the case OpenAPI needs a synthesised schema for and Smithy names itself.
    /// </summary>
    [HardenedTest]
    public async Task CreatePet_BindsTheInputStructureAsTheBody(ITestWebApp app) {
        var response = await app.Post(new { name = "Whiskers", kind = "cat" }, "/pets");

        response.Assert.Ok();

        var output = response.Deserialize<CreatePetOutput>();

        Assert.NotNull(output);
        Assert.Equal("Whiskers", output.Pet.Name);
    }

    /// <summary>
    /// The model says <c>@http(code: 201)</c> and the response is 200.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <b>This asserts a known gap, not the desired behaviour.</b> <c>SuccessStatusCode</c> is
    /// parsed, carried through the serialized model, and read in exactly one place -
    /// <c>ServiceInterfaceEmitter</c>, where it becomes the <c>&rarr; 201</c> in a doc comment.
    /// Nothing applies it to the response, so a description that promises 201 Created answers 200.
    /// </para>
    /// <para>
    /// It is not a Smithy problem and not new: the OpenAPI fixture's petstore.yaml declares a
    /// <c>'201'</c> for the same operation and has no test that would notice. Fixing it changes the
    /// status every spec-first application returns, which is a decision about the whole pipeline
    /// rather than about this front end - so it is pinned here instead, and this test will fail the
    /// moment someone fixes it, which is when it should be revisited.
    /// </para>
    /// </remarks>
    [HardenedTest]
    public async Task CreatePet_DoesNotYetApplyTheDeclaredStatusCode(ITestWebApp app) {
        var response = await app.Post(new { name = "Rex" }, "/pets");

        Assert.Equal(200, response.StatusCode);
    }

    /// <summary>@length(min: 1, max: 64) on the name member.</summary>
    [HardenedTest]
    public async Task CreatePet_RejectsANameLongerThanTheDeclaredLength(ITestWebApp app) {
        var response = await app.Post(new { name = new string('x', 65) }, "/pets");

        response.Assert.BadRequest();
    }

    /// <summary>
    /// An enum member is <c>DOG</c> in the model and <c>dog</c> on the wire, because Smithy carries
    /// both and the generated converter uses the second.
    /// </summary>
    [HardenedTest]
    public async Task CreatePet_SerialisesAnEnumByItsWireValue(ITestWebApp app) {
        var response = await app.Post(new { name = "Rex", kind = "dog" }, "/pets");

        response.Assert.Ok();

        // Read verbatim rather than deserialised: the point is the bytes on the wire say "dog", the
        // model's @enumValue, and not "DOG", the member name the C# enum is built from.
        response.Body.Position = 0;
        var body = await new StreamReader(response.Body).ReadToEndAsync();

        Assert.Contains("\"dog\"", body);
        Assert.DoesNotContain("\"DOG\"", body);
    }

    [HardenedTest]
    public async Task UnknownRoute_IsNotFound(ITestWebApp app) {
        var response = await app.Get("/pets/1/toys");

        response.Assert.NotFound();
    }
}
