using Hardened.Requests.Abstract.Headers;
using Hardened.Requests.Runtime.Validation;
using Hardened.Web.Runtime.Responses;

namespace Hardened.IntegrationTests.Smithy.SUT.Tests;

/// <summary>
/// A Smithy-described service, served.
/// </summary>
/// <remarks>
/// The parser tests assert what the reader produces and the task tests assert what reaches disk.
/// These assert the only thing that actually matters to someone using this: that a request arrives
/// at the right handler with its parameters bound, its constraints enforced and its response
/// serialised - through routing, binding, validation and JSON that were all generated by code with
/// no knowledge of Smithy.
/// </remarks>
public class PetStoreRoutingTests
{
    [ModuleTest]
    public async Task GetPet_BindsThePathLabel(ITestWebApp app)
    {
        var response = await app.Get("/pets/1");

        response.Assert.Ok();

        var output = response.Deserialize<GetPetOutput>();

        Assert.NotNull(output);
        Assert.Equal("1", output.Pet.Id);
        Assert.Equal("Buddy", output.Pet.Name);
    }

    /// <summary>
    /// The member is called <c>detailed</c> in the model and binds under <c>verbose</c>, which is
    /// what <c>@httpQuery("verbose")</c> says. The wire name is the contract.
    /// </summary>
    [ModuleTest]
    public async Task GetPet_BindsTheQueryParameterUnderItsWireName(ITestWebApp app)
    {
        var withNickname = await app.Get("/pets/2?verbose=true");
        var withoutNickname = await app.Get("/pets/2?verbose=false");

        withNickname.Assert.Ok();
        withoutNickname.Assert.Ok();

        Assert.Equal("Lu", withNickname.Deserialize<GetPetOutput>()!.Pet.Nickname);
        Assert.Null(withoutNickname.Deserialize<GetPetOutput>()!.Pet.Nickname);
    }

    /// <summary>
    /// <c>@pattern</c> on a path label is validation, as it is on a body member: a value violating
    /// it answers 400 naming the label.
    /// </summary>
    /// <remarks>
    /// This answered 404 with no body while the pattern was compiled into the route, under an
    /// operation whose model declares its 404 with a <c>PetNotFound</c> body. A generated client
    /// read that 404 as a <c>PetNotFound</c> and failed. The pattern stays in the route only where
    /// two operations share a route's shape and it is what tells them apart.
    /// </remarks>
    [ModuleTest]
    public async Task GetPet_RefusesAPathLabelFailingThePattern(ITestWebApp app)
    {
        var response = await app.Get("/pets/NOT_VALID");

        response.Assert.BadRequest();

        var error = response.Deserialize<RequestValidationError>();

        Assert.Contains(error!.Errors, e => e.Field == "petId" && e.Code == "pattern");
    }

    [ModuleTest]
    public async Task ListPets_ReturnsTheCollection(ITestWebApp app)
    {
        var response = await app.Get("/pets");

        response.Assert.Ok();

        var output = response.Deserialize<ListPetsOutput>();

        Assert.NotNull(output);
        Assert.Equal(2, output.Pets.Count);
    }

    [ModuleTest]
    public async Task ListPets_BindsTheQueryParameter(ITestWebApp app)
    {
        var response = await app.Get("/pets?limit=1");

        response.Assert.Ok();
        Assert.Single(response.Deserialize<ListPetsOutput>()!.Pets);
    }

    /// <summary>@range(min: 1, max: 100) on the query member.</summary>
    [ModuleTest]
    public async Task ListPets_RejectsALimitOutsideTheDeclaredRange(ITestWebApp app)
    {
        var response = await app.Get("/pets?limit=500");

        response.Assert.BadRequest();
    }

    /// <summary>
    /// Every member of the input structure carries no binding trait, so the whole structure is the
    /// JSON body - the case OpenAPI needs a synthesised schema for and Smithy names itself.
    /// </summary>
    [ModuleTest]
    public async Task CreatePet_BindsTheInputStructureAsTheBody(ITestWebApp app)
    {
        var response = await app.Post(new { name = "Whiskers", kind = "cat" }, "/pets");

        response.Assert.Ok();

        var output = response.Deserialize<CreatePetOutput>();

        Assert.NotNull(output);
        Assert.Equal("Whiskers", output.Pet.Name);
    }

    /// <summary>
    /// The model says <c>@http(code: 201)</c> and the response is 201.
    /// </summary>
    /// <remarks>
    /// <para>
    /// This asserted the opposite until 2026-08-20, as a pinned known gap: <c>SuccessStatusCode</c>
    /// was parsed, carried through the serialized model, and read in exactly one place -
    /// <c>ServiceInterfaceEmitter</c>, where it became the <c>&rarr; 201</c> in a doc comment.
    /// Nothing applied it, so a description promising 201 Created answered 200 and a client
    /// generated from it was wrong about every creation endpoint.
    /// </para>
    /// <para>
    /// The note left here said the fix changes the status every specification-first application
    /// returns and so was a decision about the whole pipeline rather than about this front end, and
    /// that the test would fail the moment someone made it. It did, and this is the revisit: the
    /// status now reaches <c>IExecutionRequestHandlerInfo.SuccessStatus</c> from both front ends and
    /// is applied once, in <c>ContextSerializationService</c>.
    /// </para>
    /// </remarks>
    [ModuleTest]
    public async Task CreatePet_AppliesTheDeclaredStatusCode(ITestWebApp app)
    {
        var response = await app.Post(new { name = "Rex" }, "/pets");

        Assert.Equal(201, response.StatusCode);
    }

    /// <summary>@length(min: 1, max: 64) on the name member.</summary>
    [ModuleTest]
    public async Task CreatePet_RejectsANameLongerThanTheDeclaredLength(ITestWebApp app)
    {
        var response = await app.Post(new { name = new string('x', 65) }, "/pets");

        response.Assert.BadRequest();
    }

    /// <summary>
    /// An enum member is <c>DOG</c> in the model and <c>dog</c> on the wire, because Smithy carries
    /// both and the generated converter uses the second.
    /// </summary>
    [ModuleTest]
    public async Task CreatePet_SerialisesAnEnumByItsWireValue(ITestWebApp app)
    {
        var response = await app.Post(new { name = "Rex", kind = "dog" }, "/pets");

        response.Assert.Ok();

        // Read verbatim rather than deserialised: the point is the bytes on the wire say "dog", the
        // model's @enumValue, and not "DOG", the member name the C# enum is built from.
        response.Body.Position = 0;
        var body = await new StreamReader(response.Body).ReadToEndAsync();

        Assert.Contains("\"dog\"", body);
        Assert.DoesNotContain("\"DOG\"", body);
    }

    [ModuleTest]
    public async Task UnknownRoute_IsNotFound(ITestWebApp app)
    {
        var response = await app.Get("/pets/1/toys");

        response.Assert.NotFound();
    }

    /// <summary>
    /// A miss answers the shape the model declared for the status, not an empty body.
    /// </summary>
    /// <remarks>
    /// <para>
    /// GetPet returns null for a pet it does not hold, which is a 404. PetNotFound is an
    /// <c>@error</c> with a <c>@required message</c>, and nothing in the request says what that
    /// message should be - so the response used to carry the status and no body at all, while the
    /// served document promised the shape. A generated client registers that shape for the status,
    /// finds nothing to deserialize and throws a bare transport exception rather than the typed
    /// error, which is how the defect was found.
    /// </para>
    /// <para>
    /// The message is the status's reason phrase, because that is the whole of what is known here:
    /// Smithy gives <c>message</c> one meaning, so filling it is conformance, and nothing invents
    /// a reason the handler did not give. A handler with something to say throws
    /// <c>new PetNotFound("...").AsException()</c> instead, as the Throttled route does.
    /// </para>
    /// </remarks>
    [ModuleTest]
    public async Task GetPet_AnswersAMissWithTheDeclaredErrorShape(ITestWebApp app)
    {
        var response = await app.Get("/pets/no-such-pet");

        response.Assert.NotFound();

        var error = response.Deserialize<PetNotFound>();

        Assert.NotNull(error);
        Assert.Equal("Not Found", error.Message);
    }

    /// <summary>
    /// The framework's <c>NotFound</c>, thrown, answers the shape the model declares for 404, with
    /// the record's detail as its message.
    /// </summary>
    /// <remarks>
    /// Response mode converts a returned <c>NotFound</c> into the declared case. Throws mode sent
    /// the framework's problem document instead, which the model does not declare at 404, so a
    /// generated client read a <c>PetNotFound</c> whose message was null.
    /// </remarks>
    [ModuleTest]
    public async Task GetPet_AThrownNotFoundAnswersTheDeclaredErrorShape(ITestWebApp app)
    {
        var response = await app.Get("/pets/rehomed");

        response.Assert.NotFound();

        Assert.Equal("Pet rehomed has a new home.", response.Deserialize<PetNotFound>().Message);
        Assert.DoesNotContain("resource", await response.ReadTextAsync());
    }

    /// <summary>
    /// An <c>@httpPayload</c> blob is the raw request body, so bytes that are not JSON reach the
    /// handler unchanged.
    /// </summary>
    /// <remarks>
    /// The payload was read as a base64 JSON string, so these bytes answered 400 while the served
    /// document declared a binary body.
    /// </remarks>
    [ModuleTest]
    public async Task PutPetPhoto_ReadsTheRawBytes(ITestWebApp app)
    {
        byte[] photo = [0xFF, 0xD8, 0xFF, 0xE0, 0x00, 0x7F, 0x91, 0xC3];

        var response = await app.Put(
            photo,
            "/pets/1/photo",
            request => request.Headers[KnownHeaders.ContentType] = "image/jpeg"
        );

        response.Assert.Ok();

        Assert.Equal(photo.Length, response.Deserialize<PutPetPhotoOutput>().ByteCount);
    }
}
