<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>.net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>true</IsPackable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Amazon.Lambda.SQSEvents" Version="2.2.0" />
      <PackageReference Include="Hardened.Library.SourceGenerator" Version="0.1.0-Alpha1152" />
      <PackageReference Include="Hardened.Requests.Runtime" Version="0.1.0-Alpha1152" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Function\Hardened.Amz.Function.Lambda.Runtime\Hardened.Amz.Function.Lambda.Runtime.csproj" />
    </ItemGroup>

</Project>
