<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Description>API Gateway hosting for Hardened web applications. Maps API Gateway proxy events onto the Hardened execution pipeline.</Description>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>True</IsPackable>
        <PackageId>Hardened.Amz.Web.Lambda.Runtime</PackageId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Amazon.Lambda.APIGatewayEvents" Version="2.7.0" />
        <PackageReference Include="Amazon.Lambda.Core" Version="2.2.0" />
        <PackageReference Include="Amazon.Lambda.Logging.AspNetCore" Version="3.1.0"/>
        <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="2.4.3" />
        <PackageReference Include="DependencyModules.Runtime" Version="1.0.0-rc9200" />
        <PackageReference Include="DependencyModules.SourceGenerator" Version="1.0.0-rc9200" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
        <PackageReference Include="Hardened.Requests.Abstract" Version="1.0.0-preview*" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.1" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.1" />
        <PackageReference Include="Microsoft.Extensions.Primitives" Version="8.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Shared\Hardened.Amz.Shared.Lambda.Runtime\Hardened.Amz.Shared.Lambda.Runtime.csproj" />
    </ItemGroup>


</Project>
