// <auto-generated/>
#nullable enable
#pragma warning disable CS1591 // generated members carry no doc comments
using Hardened.Requests.Abstract.Links;
using System;
using TestApp;

namespace TestApp
{
    public partial class Application
    {

        /// <summary>
        /// The routes Application declares, as paths. For a link a client can call, use Application.Links.
        /// </summary>
        public static class Routes
        {

            public static class Search
            {

                public static string SearchGet(global::System.String category)
                {
                    return "/search/" + global::System.Uri.EscapeDataString(category);
                }
            }
        }

        /// <summary>
        /// Links to Application's routes, as a client would call them. Resolve from the container, or read it off a template.
        /// </summary>
        public sealed class Links
        {
            private readonly global::Hardened.Requests.Abstract.Links.ILinkContext _context;
            private global::TestApp.Application.Links.SearchLinks? _Search;

            public Links(global::Hardened.Requests.Abstract.Links.ILinkContext context)
            {
                _context = context;
            }

            public global::TestApp.Application.Links.SearchLinks Search => _Search ??= new SearchLinks(_context);

            public sealed class SearchLinks
            {
                private readonly global::Hardened.Requests.Abstract.Links.ILinkContext _context;

                public SearchLinks(global::Hardened.Requests.Abstract.Links.ILinkContext context)
                {
                    _context = context;
                }

                public string SearchGet(global::System.String category)
                {
                    return _context.Resolve(global::TestApp.Application.Routes.Search.SearchGet(category));
                }

                public string SearchGetAbsolute(global::System.String category)
                {
                    return _context.Absolute(global::TestApp.Application.Routes.Search.SearchGet(category));
                }
            }
        }
    }
}
