// <auto-generated/>
#nullable enable
#pragma warning disable CS1591 // generated members carry no doc comments
namespace TestApp.Generated
{
    public partial class SearchController_Search_1653 : global::Hardened.Requests.Runtime.Execution.BaseExecutionHandler<global::TestApp.SearchController>
    {
        private static readonly global::Hardened.Requests.Abstract.Execution.IExecutionRequestParameter[] _parameterInfo =         CreateParameterInfo()
;
        private static readonly global::Hardened.Requests.Runtime.Execution.ExecutionRequestHandlerInfo _handlerInfo =         new global::Hardened.Requests.Runtime.Execution.ExecutionRequestHandlerInfo("/search/{category}", "GET", typeof(global::TestApp.SearchController), "Search", _parameterInfo)
;

        public SearchController_Search_1653(global::System.IServiceProvider serviceProvider, string? routePath = null)
            : base(global::Hardened.Requests.Runtime.Execution.ExecutionHelper.AsyncStandardFilterWithParameters<
            global::TestApp.SearchController,
            global::TestApp.Generated.SearchController_Search_1653.Parameters
        >(
            serviceProvider,
            _handlerInfo.WithPath(routePath),
            BindRequestParameters,
            InvokeMethod,
            global::Hardened.Requests.Runtime.Execution.ExecutionHelper.GetFilterInfo()
        ), null)
        {
        }

        private static global::Hardened.Requests.Abstract.Execution.IExecutionRequestParameter[] CreateParameterInfo()
        {
            var returnArray = new global::Hardened.Requests.Abstract.Execution.IExecutionRequestParameter[2];
            returnArray[0] = new global::Hardened.Requests.Runtime.Execution.ExecutionRequestParameter(
                "category",
                0,
                typeof(global::System.String)
            );
            returnArray[1] = new global::Hardened.Requests.Runtime.Execution.ExecutionRequestParameter(
                "limit",
                1,
                typeof(int)
            );
            return returnArray;
        }

        private static async global::System.Threading.Tasks.Task InvokeMethod(global::Hardened.Requests.Abstract.Execution.IExecutionContext context, global::TestApp.SearchController controller, global::TestApp.Generated.SearchController_Search_1653.Parameters parameters)
        {
            context.Response.ResponseValue = await controller.Search(
                parameters.category,
                parameters.limit
            );
        }

        private static global::System.Threading.Tasks.Task<global::Hardened.Requests.Abstract.Execution.IExecutionRequestParameters> BindRequestParameters(global::Hardened.Requests.Abstract.Execution.IExecutionContext context)
        {
            var parameters = new global::TestApp.Generated.SearchController_Search_1653.Parameters();
            parameters.category = context.KnownServices.StringConverterService.ParseRequired<global::System.String>(
                context.Request.PathTokens.Get("category")!,
                "category"
            );
            parameters.limit = context.KnownServices.StringConverterService.ParseOptional<int?>(
                context.Request.QueryString.Get("limit")!,
                "limit"
            );
            return global::System.Threading.Tasks.Task.FromResult<global::Hardened.Requests.Abstract.Execution.IExecutionRequestParameters>(parameters);
        }

        public partial class Parameters : global::Hardened.Requests.Runtime.Execution.ExecutionRequestParameters
        {

            public global::System.String category { get; set; } = default!;

            public int? limit { get; set; } = default!;

            public override object this[int index]
            {
                get
                {
                    switch (index)
                    {
                        case 0:
                            return this.category!;
                        case 1:
                            return this.limit!;
                    }
                    throw new global::System.IndexOutOfRangeException("Index out of range, parameters count 2, index was " + index);
                }
                set
                {
                    switch (index)
                    {
                        case 0:
                            this.category = (global::System.String)value;
                            return;
                        case 1:
                            this.limit = (int?)value;
                            return;
                    }
                    throw new global::System.IndexOutOfRangeException("Index out of range, parameters count 2, index was " + index);
                }
            }

            public override global::System.Collections.Generic.IReadOnlyList<global::Hardened.Requests.Abstract.Execution.IExecutionRequestParameter> Info => _parameterInfo;
        }
    }
}
