<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Description>Test support for Hardened DynamoDB Streams handlers.</Description>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>True</IsPackable>
        <PackageId>Hardened.Amz.Function.DDB.Testing</PackageId>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Amazon.Lambda.DynamoDBEvents" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Function\Hardened.Amz.Function.Lambda.Testing\Hardened.Amz.Function.Lambda.Testing.csproj" />
      <ProjectReference Include="..\Hardened.Amz.Function.DDB.Runtime\Hardened.Amz.Function.DDB.Runtime.csproj" />
    </ItemGroup>

</Project>
