<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Hardened.Shared.Testing" Version="0.1.0-Alpha1150" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.0" />
        <PackageReference Include="xunit" Version="2.9.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Lambda\DynamoDbStream\Hardened.Amz.Function.DDB.Testing\Hardened.Amz.Function.DDB.Testing.csproj" />
      <ProjectReference Include="..\..\Lambda\Function\Hardened.Amz.Function.Lambda.Testing\Hardened.Amz.Function.Lambda.Testing.csproj" />
      <ProjectReference Include="..\DynamoDbStreamApp\DynamoDbStreamApp.csproj" />
    </ItemGroup>
</Project>
