<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>.net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>True</IsPackable>
        <PackageId>Hardened.Amz.Function.Lambda.Streaming</PackageId>
        <Authors>Ian Johnson</Authors>
        <PackageTags>Hardened.Framework</PackageTags>
        <PackageProjectUrl>https://github.com/ipjohnson/Hardened.Framework</PackageProjectUrl>
        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://github.com/ipjohnson/Hardened.Framework</RepositoryUrl>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Amazon.Lambda.Core" Version="2.2.0" />
        <PackageReference Include="DependencyModules.Runtime" Version="1.0.0-*" />
        <PackageReference Include="DependencyModules.SourceGenerator" Version="1.0.0-*" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
        <PackageReference Include="Hardened.Requests.Abstract" Version="0.2.0-*" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.1" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.1" />
        <PackageReference Include="Microsoft.Extensions.Primitives" Version="8.0.0" />
        <PackageReference Include="System.IO.Pipelines" Version="8.0.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Shared\Hardened.Amz.Shared.Lambda.Runtime\Hardened.Amz.Shared.Lambda.Runtime.csproj" />
        <ProjectReference Include="..\Hardened.Amz.Function.Lambda.Runtime\Hardened.Amz.Function.Lambda.Runtime.csproj" />
    </ItemGroup>

</Project>
