<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Description>AWS Lambda response streaming for Hardened function handlers.</Description>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>True</IsPackable>
        <PackageId>Hardened.Amz.Function.Lambda.Streaming</PackageId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Amazon.Lambda.Core" />
        <PackageReference Include="DependencyModules.Runtime" />
        <PackageReference Include="DependencyModules.SourceGenerator" OutputItemType="Analyzer" ReferenceOutputAssembly="false" PrivateAssets="all" />
        <PackageReference Include="Hardened.Requests.Abstract" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.Primitives" />
        <PackageReference Include="System.IO.Pipelines" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Shared\Hardened.Amz.Shared.Lambda.Runtime\Hardened.Amz.Shared.Lambda.Runtime.csproj" />
        <ProjectReference Include="..\Hardened.Amz.Function.Lambda.Runtime\Hardened.Amz.Function.Lambda.Runtime.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="DependencyInjection\" />
    </ItemGroup>

</Project>
