// <auto-generated/>
#nullable enable
#pragma warning disable CS1591 // generated members carry no doc comments
namespace TestApp
{
    public partial class Application
    {

        /// <summary>
        /// The routes Application declares, as paths. For a link a client can call, use Application.Links.
        /// </summary>
        public static class Routes
        {

            public static class SignUp
            {

                public static string SignUpPost()
                {
                    return "/sign-up";
                }
            }
        }

        /// <summary>
        /// Links to Application's routes, as a client would call them. Resolve from the container, or read it off a template.
        /// </summary>
        public sealed class Links
        {
            private readonly global::Hardened.Requests.Abstract.Links.ILinkContext _context;
            private global::TestApp.Application.Links.SignUpLinks? _SignUp;

            public Links(global::Hardened.Requests.Abstract.Links.ILinkContext context)
            {
                _context = context;
            }

            public global::TestApp.Application.Links.SignUpLinks SignUp => _SignUp ??= new SignUpLinks(_context);

            public sealed class SignUpLinks
            {
                private readonly global::Hardened.Requests.Abstract.Links.ILinkContext _context;

                public SignUpLinks(global::Hardened.Requests.Abstract.Links.ILinkContext context)
                {
                    _context = context;
                }

                public string SignUpPost()
                {
                    return _context.Resolve(global::TestApp.Application.Routes.SignUp.SignUpPost());
                }

                public string SignUpPostAbsolute()
                {
                    return _context.Absolute(global::TestApp.Application.Routes.SignUp.SignUpPost());
                }
            }
        }
    }
}
