using Hardened.SourceGenerator.Shared;
using Xunit;

namespace Hardened.SourceGenerator.Tests.Shared;

/// <summary>
/// The header every generated file carries.
/// </summary>
/// <remarks>
/// Three lines that are read by three different things, which is why they travel together. The
/// marker is what an analyzer honours. CS1591 is a compiler warning and honours neither the marker
/// nor the file name, so only the pragma quiets it - without it, turning on
/// <c>GenerateDocumentationFile</c> reported 1,436 warnings against one integration application,
/// 560 from a single generated links file. And a file recognised as generated needs an explicit
/// nullable context or its annotations are CS8669, so the marker without the directive turns a
/// quiet build into a broken one.
/// </remarks>
public class GeneratedSourceTests {

    [Fact]
    public void TheMarkerIsTheFirstThingInTheFile() =>
        Assert.StartsWith("// <auto-generated/>\n", GeneratedSource.Header("class C;"));

    [Fact]
    public void TheNullableContextIsDeclared() =>
        Assert.Contains("#nullable enable", GeneratedSource.Header("class C;"));

    [Fact]
    public void TheDocCommentWarningIsDisabled() =>
        Assert.Contains("#pragma warning disable CS1591", GeneratedSource.Header("class C;"));

    [Fact]
    public void TheSourceSurvivesUnchanged() =>
        Assert.EndsWith("class C;", GeneratedSource.Header("class C;"));

    /// <summary>
    /// Applying it twice does not stack, so a generator that already wrote the header keeps one.
    /// </summary>
    [Fact]
    public void AFileThatAlreadyCarriesTheHeaderIsLeftAlone() {
        var once = GeneratedSource.Header("class C;");

        Assert.Equal(once, GeneratedSource.Header(once));
    }
}
