<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(HardenedTargetFramework)</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Shared\Hardened.Shared.Runtime.Tests\Hardened.Shared.Runtime.Tests.csproj"/>
        <ProjectReference Include="..\Hardened.Requests.Testing\Hardened.Requests.Testing.csproj"/>
    </ItemGroup>

</Project>
