using System.Collections.Immutable;
using System.Linq;
using Hardened.SourceGenerator.Shared;
using Hardened.SourceGenerator.Validation;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using ValidationModules.SourceGenerator.Impl;
using ValidationModules.SourceGenerator.Impl.Emitters;
using ValidationModules.SourceGenerator.Impl.FrontEnds;
using ValidationModules.SourceGenerator.Impl.Models;

namespace Hardened.Validation.SourceGenerator;

/// <summary>
/// Turns constraint attributes into validators, and registers them into the application's entry
/// point so nothing has to be wired by hand.
/// </summary>
/// <remarks>
/// <para>
/// <b>One scan, one path.</b> A model a developer wrote and a model the OpenAPI build task emitted
/// are the same thing here: both are ordinary source in the compilation, both carry attributes, and
/// both are read by ValidationModules' own front-end. There is no spec-aware code in this generator
/// at all - the task's job is to put attributes on what it emits, and this picks them up like
/// anything else. <c>[Required]</c> on a hand-written class needs no wiring beyond referencing the
/// package.
/// </para>
/// <para>
/// <b>Both attribute vocabularies.</b> ValidationModules' own constraints and
/// <c>System.ComponentModel.DataAnnotations</c> reach the same IR through the same front-end, so
/// <c>[StringLength(1, 100)]</c> from either namespace produces the same validator.
/// </para>
/// <para>
/// <b>Why registration lands in the entry point.</b> DependencyModules keys registrations on the
/// entry point type - <c>DependencyRegistry&lt;TEntryPoint&gt;</c> - and composes sibling modules
/// only through attributes someone writes. A module emitted beside the entry point would sit there
/// unreferenced. Naming the entry point and adding to its registry is what the routing table
/// already does, and it means a consumer calls nothing.
/// </para>
/// </remarks>
[Generator]
public class HardenedValidationGenerator : IIncrementalGenerator {

    /// <summary>
    /// Deliberately plain C#: block-scoped namespace, ordinary class body, no nullable context.
    /// This lands in whatever project references the generator, and a marker that needs a language
    /// version to compile would fail the builds it exists to keep working.
    /// </summary>
    private const string MarkerSource =
        "// <auto-generated/>\n" +
        "namespace Hardened.Validation.Generated {\n" +
        "    /// <summary>Declared by Hardened.Validation.SourceGenerator so other generators can tell\n" +
        "    /// whether validators are being emitted for this compilation.</summary>\n" +
        "    internal static class ValidationGeneratorMarker {\n" +
        "    }\n" +
        "}\n";

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        // Says "this generator is running" to the handler generators, which emit calls to
        // validators this one produces and would otherwise name types nobody declares. Post-init
        // because that is the only generated source another generator can see.
        context.RegisterPostInitializationOutput(static production => production.AddSource("Hardened.Validation.Marker.g.cs", GeneratedSource.Header(MarkerSource)));

        var options = context.AnalyzerConfigOptionsProvider
            .Select(static (provider, _) => ValidationGeneratorOptions.Read(provider));

        var candidates = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is TypeDeclarationSyntax,
                static (syntaxContext, _) => {
                    var symbol = syntaxContext.SemanticModel.GetDeclaredSymbol(syntaxContext.Node)
                        as INamedTypeSymbol;

                    // One declaration per type, not one per declaration site.
                    //
                    // The predicate above fires for every TypeDeclarationSyntax, and a partial type
                    // has one of those per file it is declared in - while GetDeclaredSymbol returns
                    // the same merged symbol for all of them. BuildModel reads only the symbol, so
                    // each declaration produced an identical model, an identical hint name, and
                    // AddSource threw on the second.
                    //
                    // Roslyn reports that as CS8785, a *warning*: the generator died, every
                    // validator in the compilation went with it, and the build succeeded. Five legal
                    // lines - a computed property on a generated partial record - were enough, and
                    // generating models as partial is an invitation to write exactly those lines.
                    return symbol is not null && DeclaresPrimarily(symbol, syntaxContext.Node)
                        ? symbol
                        : null;
                })
            .Where(static symbol => symbol is not null)
            .Select(static (symbol, _) => symbol!);

        var models = candidates
            .Combine(options)
            .Combine(context.CompilationProvider)
            .Select(static (pair, _) => BuildModel(pair.Left.Left, pair.Left.Right, pair.Right))
            .Where(static result => result.Model is not null || result.Diagnostics.Length > 0);

        context.RegisterSourceOutput(models, static (production, result) => {
            foreach (var diagnostic in result.Diagnostics) {
                production.ReportDiagnostic(diagnostic);
            }

            if (result.Model is { } model) {
                // Guarded because the alternative is silence. An AddSource that throws takes the
                // generator down mid-run, Roslyn reports the death as CS8785 - a warning - and the
                // build succeeds having emitted no validators at all. A named diagnostic costs one
                // catch and means the next occurrence of this shape says what happened.
                try {
                    production.AddSource(
                        HintNameFor(model), GeneratedSource.Header(new ValidatorEmitter().Emit(model)));
                } catch (ArgumentException exception) {
                    production.ReportDiagnostic(
                        ValidationGeneratorDiagnostics.DuplicateValidatorSource(model, exception));
                }
            }
        });

        var entryPoint = context.SyntaxProvider.CreateSyntaxProvider(
                EntryPointSelector.UsingAttribute(),
                EntryPointSelector.TransformModel(false))
            .WithComparer(new EntryPointSelector.Comparer());

        var validators = models
            .Select(static (result, _) => result.Model)
            .Where(static model => model is not null)
            .Select(static (model, _) => model!)
            .Collect();

        context.RegisterSourceOutput(entryPoint.Combine(validators), static (production, pair) =>
            RegistrationWriter.Write(production, pair.Left, pair.Right));
    }

    /// <summary>
    /// Whether <paramref name="node"/> is the declaration this generator answers for
    /// <paramref name="symbol"/>, so a partial type is emitted once rather than once per file.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The first declaring reference wins, arbitrarily but consistently - every declaration of a
    /// partial type resolves to the same symbol, and the model is built from the symbol alone, so
    /// which one is chosen cannot change what is emitted. Only how many times.
    /// </para>
    /// <para>
    /// Compared by tree and span rather than by node identity: the reference holds a position, and
    /// resolving it with <c>GetSyntax()</c> would reparse for a comparison two integers answer.
    /// </para>
    /// </remarks>
    private static bool DeclaresPrimarily(INamedTypeSymbol symbol, SyntaxNode node) {
        var references = symbol.DeclaringSyntaxReferences;

        if (references.Length <= 1) {
            return true;
        }

        var first = references[0];

        return first.SyntaxTree == node.SyntaxTree && first.Span == node.Span;
    }

    /// <summary>
    /// The file a validator is added under, which Roslyn requires to be unique per generator.
    /// </summary>
    /// <remarks>
    /// Qualified by namespace: the type name is not unique on its own, and two namespaces in one
    /// assembly each declaring a <c>Customer</c> would collide. <c>AddSource</c> throws on a
    /// duplicate, which fails the whole generator rather than the second type.
    /// </remarks>
    private static string HintNameFor(ValidatedTypeModel model) =>
        model.Namespace.Length == 0
            ? $"{model.ValidatorName}.g.cs"
            : $"{model.Namespace}.{model.ValidatorName}.g.cs";

    private static ModelResult BuildModel(
        INamedTypeSymbol symbol, ValidationGeneratorOptions options, Compilation compilation) {
        var frontEnd = new AttributeFrontEnd(
            compilation, options.CompileDataAnnotations, options.FieldNamer, options.ResolvedPatternPolicy);

        var model = frontEnd.Build(symbol, ValidationGeneratorOptions.ValidatorNameFor);

        var diagnostics = frontEnd.Diagnostics.ToList();

        diagnostics.AddRange(RequiredValueTypesThatCannotBeMissed(symbol));
        diagnostics.AddRange(UnreachableNestedConstraints(symbol, model));

        return new ModelResult(model, diagnostics.ToImmutableArray());
    }

    /// <summary>
    /// Members whose type declares constraints that this type's validator will never reach.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The generated validator descends into a member only where <c>[ValidateNested]</c> says to,
    /// so omitting it silently switches off every constraint on the child type. The generator
    /// compiled those constraints and can see the property that fails to reach them, which is what
    /// makes this sayable at all.
    /// </para>
    /// <para>
    /// Sited on the symbol rather than the built model for the reason the required-value-type check
    /// is: what decides it is the member's C# type and the child type's attributes, and the
    /// validation IR has already resolved both away.
    /// </para>
    /// <para>
    /// Only child types declared in this compilation are considered. Those are the ones this
    /// generator emits validators for, so "a constraint that just became unreachable" is knowable
    /// rather than guessed at - a type from a package may have been validated at its own boundary.
    /// </para>
    /// <para>
    /// And only parents that constrain something themselves. Every type declaration in the
    /// compilation reaches this generator, most of which are not models at all - a data seed
    /// holding a list of records, a response case wrapping a body - and a validator that checks
    /// nothing was never going to descend anywhere. What the warning is about is a model that
    /// validates, with one property the validation stops at.
    /// </para>
    /// </remarks>
    private static IEnumerable<Diagnostic> UnreachableNestedConstraints(
        INamedTypeSymbol symbol, ValidatedTypeModel? model) {
        if (!Constrains(model)) {
            yield break;
        }

        foreach (var member in symbol.GetMembers()) {
            if (member is not IPropertySymbol property || property.IsStatic ||
                property.DeclaredAccessibility != Accessibility.Public) {
                continue;
            }

            if (DeclaresValidateNested(property)) {
                continue;
            }

            var nested = NestedType(property.Type, out var isElement);

            if (nested == null || SymbolEqualityComparer.Default.Equals(nested, symbol) ||
                !DeclaredInSource(nested) || !CarriesConstraints(nested)) {
                continue;
            }

            yield return ValidationGeneratorDiagnostics.UnreachableNestedConstraints(
                symbol, property, nested, isElement);
        }
    }

    /// <summary>Whether the built model checks anything at all.</summary>
    private static bool Constrains(ValidatedTypeModel? model) {
        if (model == null) {
            return false;
        }

        foreach (var property in model.Properties) {
            if (property.Constraints.Count > 0) {
                return true;
            }
        }

        return false;
    }

    private static bool DeclaresValidateNested(IPropertySymbol property) {
        foreach (var attribute in property.GetAttributes()) {
            if (attribute.AttributeClass?.ToDisplayString()
                == "ValidationModules.Constraints.ValidateNestedAttribute") {
                return true;
            }
        }

        return false;
    }

    /// <summary>
    /// The type a descent would validate: the element of a collection, the value of a dictionary,
    /// or the member's own type. Null where there is nothing with structure to descend into.
    /// </summary>
    /// <remarks>
    /// A string is a sequence of characters and never a nested model, which is why it is taken out
    /// before the enumerable test rather than after it.
    /// </remarks>
    private static INamedTypeSymbol? NestedType(ITypeSymbol type, out bool isElement) {
        isElement = false;

        if (type is IArrayTypeSymbol array) {
            isElement = true;

            return Model(array.ElementType);
        }

        if (type.SpecialType == SpecialType.System_String) {
            return null;
        }

        if (type is INamedTypeSymbol named) {
            if (named.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T) {
                return Model(named.TypeArguments[0]);
            }

            foreach (var candidate in Self(named).Concat(named.AllInterfaces)) {
                var definition = candidate.OriginalDefinition.ToDisplayString();

                if (definition is "System.Collections.Generic.IDictionary<TKey, TValue>"
                               or "System.Collections.Generic.IReadOnlyDictionary<TKey, TValue>") {
                    isElement = true;

                    return Model(candidate.TypeArguments[1]);
                }
            }

            foreach (var candidate in Self(named).Concat(named.AllInterfaces)) {
                if (candidate.OriginalDefinition.ToDisplayString()
                    == "System.Collections.Generic.IEnumerable<T>") {
                    isElement = true;

                    return Model(candidate.TypeArguments[0]);
                }
            }
        }

        return Model(type);
    }

    private static IEnumerable<INamedTypeSymbol> Self(INamedTypeSymbol type) {
        yield return type;
    }

    /// <summary>The type as something a validator could be generated for, or null.</summary>
    private static INamedTypeSymbol? Model(ITypeSymbol type) =>
        type is INamedTypeSymbol named &&
        named.TypeKind is TypeKind.Class or TypeKind.Struct &&
        named.SpecialType == SpecialType.None
            ? named
            : null;

    private static bool DeclaredInSource(INamedTypeSymbol type) {
        foreach (var location in type.Locations) {
            if (location.IsInSource) {
                return true;
            }
        }

        return false;
    }

    /// <summary>
    /// Whether any member of the type carries a constraint from either vocabulary the front end
    /// reads.
    /// </summary>
    /// <remarks>
    /// Matched by walking the attribute's base chain to <c>ValidationConstraintAttribute</c> or
    /// <c>ValidationAttribute</c> rather than by listing names: those two bases are what the front
    /// end compiles, and a list would go stale the first time either vocabulary gained a
    /// constraint. It also keeps <c>[Display]</c> and <c>[Key]</c> out, which name a member rather
    /// than constrain it.
    /// </remarks>
    private static bool CarriesConstraints(INamedTypeSymbol type) {
        foreach (var member in type.GetMembers()) {
            if (member is not IPropertySymbol property || property.IsStatic) {
                continue;
            }

            foreach (var attribute in property.GetAttributes()) {
                if (IsConstraint(attribute.AttributeClass)) {
                    return true;
                }
            }
        }

        return false;
    }

    private static bool IsConstraint(INamedTypeSymbol? attributeClass) {
        for (var type = attributeClass; type != null; type = type.BaseType) {
            var name = type.ToDisplayString();

            if (name is "ValidationModules.Constraints.ValidationConstraintAttribute"
                     or "System.ComponentModel.DataAnnotations.ValidationAttribute") {
                return true;
            }
        }

        return false;
    }

    /// <summary>
    /// Members declared required whose absence nothing can detect.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <c>[Required]</c> compiles to a null check and a value type is never null, so an omitted
    /// <c>int</c> arrives as <c>0</c>, passes, and reaches the handler as a value the caller never
    /// sent. Sited on the symbol rather than on the built model because what decides this is the
    /// member's C# type and modifiers, which the validation IR has already abstracted away.
    /// </para>
    /// <para>
    /// Spec-emitted models do not trip it: <c>SchemaEmitter</c> writes <c>[JsonRequired]</c> onto
    /// exactly this shape, so the check reads that attribute and stays quiet. Nothing here needs to
    /// know which front end produced the type - the presence of a remedy is the test.
    /// </para>
    /// </remarks>
    private static IEnumerable<Diagnostic> RequiredValueTypesThatCannotBeMissed(
        INamedTypeSymbol symbol) {
        foreach (var member in symbol.GetMembers()) {
            if (member is not IPropertySymbol property || property.IsStatic) {
                continue;
            }

            // A nullable value type has somewhere to put "absent", and a reference type is what the
            // null check was written for. Neither is at risk.
            if (!property.Type.IsValueType ||
                property.Type.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T) {
                continue;
            }

            if (!DeclaresRequired(property) || CanDetectAbsence(property)) {
                continue;
            }

            yield return ValidationGeneratorDiagnostics.RequiredValueTypeCannotBeMissed(
                symbol, property);
        }
    }

    /// <summary>
    /// Whether the member carries a required constraint, in either vocabulary the front end reads.
    /// </summary>
    private static bool DeclaresRequired(IPropertySymbol property) {
        foreach (var attribute in property.GetAttributes()) {
            var name = attribute.AttributeClass?.ToDisplayString();

            if (name is "ValidationModules.Constraints.RequiredAttribute"
                     or "System.ComponentModel.DataAnnotations.RequiredAttribute") {
                return true;
            }
        }

        return false;
    }

    /// <summary>
    /// Whether anything already makes the deserializer reject an omitted member.
    /// </summary>
    /// <remarks>
    /// The <c>required</c> modifier is checked first because it is the better answer: the
    /// reflection-based deserializer and the source-generated resolver both honour it, where
    /// <c>[JsonRequired]</c> is read by the former alone.
    /// </remarks>
    private static bool CanDetectAbsence(IPropertySymbol property) {
        if (property.IsRequired) {
            return true;
        }

        foreach (var attribute in property.GetAttributes()) {
            if (attribute.AttributeClass?.ToDisplayString()
                == "System.Text.Json.Serialization.JsonRequiredAttribute") {
                return true;
            }
        }

        return false;
    }

    private sealed record ModelResult(ValidatedTypeModel? Model, ImmutableArray<Diagnostic> Diagnostics);
}
