// <auto-generated/>
#nullable enable
#pragma warning disable CS1591 // generated members carry no doc comments
using Microsoft.Extensions.DependencyInjection;

namespace GeneratorTestAssembly.Generated
{
    public partial class Register_GET_9475be61 : global::Hardened.Requests.Runtime.Execution.BaseExecutionHandler<global::System.Func<int,global::System.Threading.Tasks.Task<int>>>
    {
        private static readonly global::Hardened.Requests.Abstract.Execution.IExecutionRequestParameter[] _parameterInfo =         CreateParameterInfo()
;
        private static readonly global::Hardened.Requests.Runtime.Execution.ExecutionRequestHandlerInfo _handlerInfo =         new global::Hardened.Requests.Runtime.Execution.ExecutionRequestHandlerInfo("(registered)", "GET", typeof(global::System.Func<int,global::System.Threading.Tasks.Task<int>>), "Invoke", _parameterInfo)
;

        public Register_GET_9475be61(global::System.IServiceProvider serviceProvider, global::System.Func<int,global::System.Threading.Tasks.Task<int>> target, string? routePath = null)
            : base(global::Hardened.Requests.Runtime.Execution.ExecutionHelper.AsyncStandardFilterWithParameters<
            global::System.Func<int,global::System.Threading.Tasks.Task<int>>,
            global::GeneratorTestAssembly.Generated.Register_GET_9475be61.Parameters
        >(
            serviceProvider,
            _handlerInfo.WithPath(routePath),
            BindRequestParameters,
            InvokeMethod,
            global::Hardened.Requests.Runtime.Execution.ExecutionHelper.GetFilterInfo(),
            handlerInstance: target
        ), null)
        {
        }

        private static global::Hardened.Requests.Abstract.Execution.IExecutionRequestParameter[] CreateParameterInfo()
        {
            var returnArray = new global::Hardened.Requests.Abstract.Execution.IExecutionRequestParameter[1];
            returnArray[0] = new global::Hardened.Requests.Runtime.Execution.ExecutionRequestParameter(
                "id",
                0,
                typeof(global::System.Int32)
            );
            return returnArray;
        }

        private static async global::System.Threading.Tasks.Task InvokeMethod(global::Hardened.Requests.Abstract.Execution.IExecutionContext context, global::System.Func<int,global::System.Threading.Tasks.Task<int>> controller, global::GeneratorTestAssembly.Generated.Register_GET_9475be61.Parameters parameters)
        {
            context.Response.ResponseValue = await controller.Invoke(parameters.id);
        }

        private static global::System.Threading.Tasks.Task<global::Hardened.Requests.Abstract.Execution.IExecutionRequestParameters> BindRequestParameters(global::Hardened.Requests.Abstract.Execution.IExecutionContext context)
        {
            var parameters = new global::GeneratorTestAssembly.Generated.Register_GET_9475be61.Parameters();
            parameters.id = context.KnownServices.StringConverterService.ParseRequired<global::System.Int32>(
                context.Request.PathTokens.Get("id")!,
                "id"
            );
            return global::System.Threading.Tasks.Task.FromResult<global::Hardened.Requests.Abstract.Execution.IExecutionRequestParameters>(parameters);
        }

        public partial class Parameters : global::Hardened.Requests.Runtime.Execution.ExecutionRequestParameters
        {

            public global::System.Int32 id { get; set; } = default!;

            public override object this[int index]
            {
                get
                {
                    switch (index)
                    {
                        case 0:
                            return this.id!;
                    }
                    throw new global::System.IndexOutOfRangeException("Index out of range, parameters count 1, index was " + index);
                }
                set
                {
                    switch (index)
                    {
                        case 0:
                            this.id = (global::System.Int32)value;
                            return;
                    }
                    throw new global::System.IndexOutOfRangeException("Index out of range, parameters count 1, index was " + index);
                }
            }

            public override global::System.Collections.Generic.IReadOnlyList<global::Hardened.Requests.Abstract.Execution.IExecutionRequestParameter> Info => _parameterInfo;
        }
    }

    /// <summary>
    /// Rewrites each registration call to one that carries the handler the build emitted for its lambda. The declared method throws; see IRouteRegistry.
    /// </summary>
    internal static class RegisteredRouteInterceptors
    {

        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "2+V918FgdYYVO4iz4gmOQssDAABUZXN0LmNz")]
public static global::Hardened.Web.Runtime.Routing.IRouteRegistry GET_0(this global::Hardened.Web.Runtime.Routing.IRouteRegistry routes, string path, global::System.Delegate handler) =>
    routes.Map(path, new global::Hardened.Web.Runtime.Routing.RegisteredRouteHandler(
        "GET",
        new string[] { "id" },
        (serviceProvider, routePath) => new global::GeneratorTestAssembly.Generated.Register_GET_9475be61(serviceProvider, (global::System.Func<int, global::System.Threading.Tasks.Task<int>>)handler, routePath),
        "\"get\":{\"tags\":[\"Func\"],\"operationId\":\"invoke\",\"parameters\":[{\"name\":\"id\",\"in\":\"path\",\"required\":true,\"schema\":{\"type\":\"integer\",\"format\":\"int32\"}}],\"responses\":{\"200\":{\"description\":\"OK\"},\"400\":{\"description\":\"The request failed validation.\",\"content\":{\"application/json\":{\"schema\":{\"$ref\":\"#/components/schemas/RequestValidationError\"}}}}}}"));
    }
}

namespace System.Runtime.CompilerServices
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : global::System.Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
            _ = version;
            _ = data;
        }
    }
}
