// <auto-generated/>
#nullable enable
#pragma warning disable CS1591 // generated members carry no doc comments
using DependencyModules.Runtime.Helpers;
using Hardened.Requests.Abstract.Execution;
using Hardened.Requests.Runtime.PathTokens;
using Hardened.Web.Runtime.Handlers;
using Hardened.Web.Runtime.Routing;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using TestApp.Generated;

namespace TestApp
{
    public partial class Application
    {
        [DynamicDependency(nameof(RoutingTableDI))]
        private static int _routingTableDependencies =         DependencyRegistry<Application>.Add(RoutingTableDI)
;

        private static void RoutingTableDI(IServiceCollection serviceCollection)
        {
            serviceCollection.AddSingleton<
                IWebExecutionRequestHandlerProvider,
                Application.RoutingTable
            >();
            serviceCollection.AddTransient<TenantController>();
            serviceCollection.AddSingleton<
                IGeneratedRouteHandlerCatalog,
                Application.RegisteredRouteHandlers
            >();
            serviceCollection.AddTransient<Application.Links>();
        }

        private class RoutingTable : IWebExecutionRequestHandlerProvider
        {
            private IServiceProvider _rootServiceProvider;
            private TenantController_Get_329? _fieldTenantController_Get_329;
            private static readonly string[] _pathTokenNamesTenantController_Get_329 =             new string[] { "id" }
;
            private static readonly RequestHandlerInfo _methodNotAllowedGETHEAD =             global::Hardened.Web.Runtime.Handlers.RequestHandlerInfo.MethodNotAllowed("GET, HEAD")
;

            public RoutingTable(IServiceProvider serviceProvider)
            {
                _rootServiceProvider = serviceProvider;
            }

            public RequestHandlerInfo? GetExecutionRequestHandler(IExecutionContext context)
            {
                var pathSpan = context.Request.Path.AsSpan();
                return TestPath_Slash(
                    pathSpan,
                    0,
                    context.Request.Method
                );
            }

            public RequestHandlerInfo? TestPath_Slash(ReadOnlySpan<char> charSpan, int index, string methodString)
            {
                RequestHandlerInfo? handlerInfo = null;
                if ((charSpan.Length >= index + 1) && (charSpan[index + 0] == '/'))
                {
                    index += 1;
                    handlerInfo = TestPath_ordersSlash(
                        charSpan,
                        index,
                        methodString
                    );
                }
                return handlerInfo;
            }

            public RequestHandlerInfo? TestPath_ordersSlash(ReadOnlySpan<char> charSpan, int index, string methodString)
            {
                RequestHandlerInfo? handlerInfo = null;
                if ((charSpan.Length >= index + 7) && (charSpan[index + 0] == 'o') && (charSpan[index + 1] == 'r') && (charSpan[index + 2] == 'd') && (charSpan[index + 3] == 'e') && (charSpan[index + 4] == 'r') && (charSpan[index + 5] == 's') && (charSpan[index + 6] == '/'))
                {
                    index += 7;
                    if (handlerInfo == null)
                    {
                        handlerInfo = TestPath_ordersSlashWildCard(
                            charSpan,
                            index,
                            methodString
                        );
                    }
                }
                return handlerInfo;
            }

            public RequestHandlerInfo? TestPath_ordersSlashWildCard(ReadOnlySpan<char> charSpan, int index, string methodString)
            {
                RequestHandlerInfo? handlerInfo = null;
                handlerInfo = TestPath_NoPathWildCardMatch(
                    charSpan,
                    index,
                    methodString
                );
                return handlerInfo;
            }

            public RequestHandlerInfo? TestPath_NoPathWildCardMatch(ReadOnlySpan<char> charSpan, int index, string methodString)
            {
                if (charSpan.Length <= index)
                {
                    return null;
                }
                if (charSpan.Slice(index).IndexOf('/') >= 0)
                {
                    return null;
                }
                if (!global::Hardened.Web.Runtime.Routing.RouteConstraints.IsInt(charSpan.Slice(index)))
                {
                    return null;
                }
                switch (methodString)
                {
                    case "HEAD":
                    case "GET":
                        return new RequestHandlerInfo(
                            _fieldTenantController_Get_329 ??= new TenantController_Get_329(_rootServiceProvider),
                            new PathTokenCollection(
                                1,
                                _pathTokenNamesTenantController_Get_329,
                                charSpan.Slice(index).ToString()
                            )
                        );
                    default:
                        return _methodNotAllowedGETHEAD;
                }
            }
        }

        /// <summary>
        /// Every handler this entry point generated, so a route registered at startup can point at one. See IGeneratedRouteHandlerCatalog.
        /// </summary>
        private sealed class RegisteredRouteHandlers : IGeneratedRouteHandlerCatalog
        {
            private static readonly GeneratedRouteHandler[] _handlers = new global::Hardened.Web.Runtime.Routing.GeneratedRouteHandler[] { new global::Hardened.Web.Runtime.Routing.GeneratedRouteHandler(typeof(global::TestApp.TenantController), "Get", "GET", "/orders/{id:int}", static (serviceProvider, routePath) => new global::TestApp.Generated.TenantController_Get_329(serviceProvider, routePath)) };
            private static readonly IReadOnlyDictionary<string,RouteConstraintTest> _constraints = new global::System.Collections.Generic.Dictionary<string, global::Hardened.Web.Runtime.Routing.RouteConstraintTest>();

            public IReadOnlyList<GeneratedRouteHandler> Handlers => _handlers;

            public bool CaseInsensitiveRoutes => false;

            public string BasePath => "";

            public IReadOnlyDictionary<string,RouteConstraintTest> Constraints => _constraints;
        }
    }
}
