// <auto-generated/>
#nullable enable
#pragma warning disable CS1591 // generated members carry no doc comments
namespace TestApp
{
    public partial class Application
    {

        /// <summary>
        /// Every handler this entry point generated, so a route registered at startup can point at one. See IGeneratedRouteHandlerCatalog.
        /// </summary>
        private sealed class RegisteredRouteHandlers : global::Hardened.Web.Runtime.Routing.IGeneratedRouteHandlerCatalog
        {
            private static readonly global::Hardened.Web.Runtime.Routing.GeneratedRouteHandler[] _handlers = new global::Hardened.Web.Runtime.Routing.GeneratedRouteHandler[] { new global::Hardened.Web.Runtime.Routing.GeneratedRouteHandler(typeof(global::TestApp.TenantController), "Get", "GET", "/orders/{id:int}", static (serviceProvider, routePath) => new global::TestApp.Generated.TenantController_Get_329(serviceProvider, routePath)) };
            private static readonly global::System.Collections.Generic.IReadOnlyDictionary<string,global::Hardened.Web.Runtime.Routing.RouteConstraintTest> _constraints = new global::System.Collections.Generic.Dictionary<string, global::Hardened.Web.Runtime.Routing.RouteConstraintTest>();

            public global::System.Collections.Generic.IReadOnlyList<global::Hardened.Web.Runtime.Routing.GeneratedRouteHandler> Handlers => _handlers;

            public bool CaseInsensitiveRoutes => false;

            public string BasePath => "";

            public global::System.Collections.Generic.IReadOnlyDictionary<string,global::Hardened.Web.Runtime.Routing.RouteConstraintTest> Constraints => _constraints;
        }
    }
}
