#!/usr/bin/env python3
"""Emits the route-scale benchmark SUTs and the catalog both sides are driven from.

Three Hardened applications, one per scale, because the Web generator hands every entry point
in a compilation the whole handler collection - so one assembly cannot hold two route sets of
different sizes without both tables containing both.

The catalog is emitted alongside them from the same list, and the benchmark asserts at setup
that every template in it matches. That is what keeps the ASP.NET side, which reads the catalog
at run time, routing the same paths as the generated controllers.
"""

import os
import textwrap

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")

# Real API nouns rather than resource001..resourceNNN. Synthetic names of one length share a
# first character, which collapses the character switch into a worst case no real application
# has, and removes the shared prefixes a radix tree exists to collapse.
RESOURCES = [
    "users", "user-preferences", "user-sessions", "user-devices",
    "orders", "order-items", "order-returns", "organizations",
    "products", "product-variants", "product-reviews", "projects",
    "payments", "payment-methods", "payouts", "invoices",
    "invoice-lines", "shipments", "shipping-zones", "subscriptions",
    "subscribers", "customers", "customer-groups", "catalogs",
    "categories", "carts", "coupons", "credits",
    "accounts", "account-limits", "addresses", "adjustments",
    "audits", "authorizations", "batches", "billing-cycles",
    "brands", "bundles", "channels", "charges",
    "checkouts", "claims", "collections", "comments",
    "contracts", "conversions", "currencies", "disputes",
    "documents", "domains", "entitlements", "events",
    "exports", "feeds", "fulfillments", "gift-cards",
    "imports", "inventories", "jobs", "ledgers",
    "locations", "manifests", "memberships", "notifications",
    "offers", "permissions", "pricing-rules", "quotas",
    "refunds", "regions", "reservations", "roles",
]

SCALES = [("Small", 2), ("Medium", 15), ("Large", 72)]

# Seven per resource. Between them they cover a literal that ends the path, a token that ends it,
# a token with a literal continuation, two tokens, a second verb at one path, and a deep
# all-literal path behind a long shared prefix.
def routes_for(resource):
    return [
        ("GET", f"/api/v1/{resource}"),
        ("POST", f"/api/v1/{resource}"),
        ("GET", f"/api/v1/{resource}/{{id}}"),
        ("DELETE", f"/api/v1/{resource}/{{id}}"),
        ("GET", f"/api/v1/{resource}/{{id}}/events"),
        ("GET", f"/api/v1/{resource}/{{id}}/events/{{eventId}}"),
        ("GET", f"/api/v1/reports/{resource}/summary/daily"),
    ]


def method_name(verb, resource, suffix):
    parts = [p.capitalize() for p in resource.split("-")]
    return verb.capitalize() + "".join(parts) + suffix


def handler_methods(resource):
    parts = [p.capitalize() for p in resource.split("-")]
    name = "".join(parts)
    return [
        ("Get", f"/api/v1/{resource}", f"List{name}", []),
        ("Post", f"/api/v1/{resource}", f"Create{name}", []),
        ("Get", f"/api/v1/{resource}/{{id}}", f"Get{name}ById", ["id"]),
        ("Delete", f"/api/v1/{resource}/{{id}}", f"Delete{name}", ["id"]),
        ("Get", f"/api/v1/{resource}/{{id}}/events", f"List{name}Events", ["id"]),
        ("Get", f"/api/v1/{resource}/{{id}}/events/{{eventId}}", f"Get{name}Event", ["id", "eventId"]),
        ("Get", f"/api/v1/reports/{resource}/summary/daily", f"Get{name}DailySummary", []),
    ]


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as handle:
        handle.write(text)
    print("wrote", os.path.relpath(path, ROOT))


def controller_source(scale, resources):
    body = []
    for resource in resources:
        for verb, template, name, tokens in handler_methods(resource):
            args = ", ".join(f"string {t}" for t in tokens)
            ret = " + ".join(tokens) if tokens else f'"{resource}"'
            body.append(f"""
    [{verb}("{template}")]
    public string {name}({args}) => {ret};""")

    return f"""// <auto-generated />
// Generated by scripts/generate-route-scale-sut.py. Do not edit by hand.
using Hardened.Web.Runtime.Attributes;

namespace Hardened.Benchmarks.RouteScale.{scale}.Sut;

/// <summary>
/// {len(resources) * 7} routes over {len(resources)} resources, for the {scale.lower()} arm of the matcher
/// comparison. The handler bodies do nothing: what is measured stops at the routing table, which
/// resolves a handler without invoking it.
/// </summary>
public class RouteScaleController
{{{"".join(body)}
}}
"""


def app_source(scale):
    return f"""// <auto-generated />
// Generated by scripts/generate-route-scale-sut.py. Do not edit by hand.
using Hardened.Shared.Runtime.Attributes;
using Hardened.Web.Runtime.DependencyInjection;

namespace Hardened.Benchmarks.RouteScale.{scale}.Sut;

[HardenedModule]
[HardenedWebModule]
public partial class RouteScale{scale}Application;
"""


def csproj_source(scale):
    return f"""<Project Sdk="Microsoft.NET.Sdk">

    <!--
      Generated by scripts/generate-route-scale-sut.py.

      One assembly per scale because WebIncrementalGenerator combines each entry point with the
      whole handler collection in its compilation, so two entry points in one assembly would both
      emit a table containing every route.
    -->
    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\\..\\Requests\\Hardened.Requests.Abstract\\Hardened.Requests.Abstract.csproj"/>
        <ProjectReference Include="..\\..\\Requests\\Hardened.Requests.Runtime\\Hardened.Requests.Runtime.csproj"/>
        <ProjectReference Include="..\\..\\Shared\\Hardened.Shared.Runtime\\Hardened.Shared.Runtime.csproj"/>
        <ProjectReference Include="..\\..\\Web\\Hardened.Web.Runtime\\Hardened.Web.Runtime.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\\..\\SourceGenerators\\Hardened.DependencyModules.SourceGenerator\\Hardened.DependencyModules.SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
        <ProjectReference Include="..\\..\\SourceGenerators\\Hardened.Library.SourceGenerator\\Hardened.Library.SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
        <ProjectReference Include="..\\..\\SourceGenerators\\Hardened.Web.SourceGenerator\\Hardened.Web.SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
    </ItemGroup>

</Project>
"""


def catalog_source():
    blocks = []
    for scale, count in SCALES:
        entries = []
        for resource in RESOURCES[:count]:
            for verb, template in routes_for(resource):
                entries.append(f'        ("{verb}", "{template}"),')
        blocks.append(f"""
    /// <summary>The {len(entries)} routes the {scale} arm declares.</summary>
    public static readonly IReadOnlyList<(string Method, string Template)> {scale} = new[]
    {{
{chr(10).join(entries)}
    }};""")

    return f"""// <auto-generated />
// Generated by scripts/generate-route-scale-sut.py. Do not edit by hand.

namespace Hardened.Benchmarks.Contracts;

/// <summary>
/// The route sets the matcher comparison runs against.
///
/// Hardened compiles its table from attributes, so its side of this list is the generated
/// controller in the matching RouteScale SUT. ASP.NET builds its DFA at run time, so its side
/// reads these templates directly. They come from one script and the benchmark asserts at setup
/// that both sides match every template, which is what stops the two arms from quietly routing
/// different applications.
/// </summary>
public static class RouteCatalog
{{{"".join(blocks)}
}}
"""


def main():
    write(os.path.join(ROOT, "src/Benchmarks/Hardened.Benchmarks.Contracts/RouteCatalog.cs"), catalog_source())

    for scale, count in SCALES:
        base = os.path.join(ROOT, f"src/Benchmarks/Hardened.Benchmarks.RouteScale.{scale}.Sut")
        write(os.path.join(base, f"Hardened.Benchmarks.RouteScale.{scale}.Sut.csproj"), csproj_source(scale))
        write(os.path.join(base, "RouteScaleApplication.cs"), app_source(scale))
        write(os.path.join(base, "RouteScaleController.cs"), controller_source(scale, RESOURCES[:count]))

    for scale, count in SCALES:
        print(f"{scale}: {count} resources, {count * 7} routes")


if __name__ == "__main__":
    main()
