// <auto-generated/>
#nullable enable
#pragma warning disable CS1591 // generated members carry no doc comments
namespace TestApp
{
    public partial class Application
    {

        /// <summary>
        /// The routes Application declares, as paths. For a link a client can call, use Application.Links.
        /// </summary>
        public static class Routes
        {

            public static class Context
            {

                public static string WhoAmI()
                {
                    return "/whoami";
                }
            }
        }

        /// <summary>
        /// Links to Application's routes, as a client would call them. Resolve from the container, or read it off a template.
        /// </summary>
        public sealed class Links
        {
            private readonly global::Hardened.Requests.Abstract.Links.ILinkContext _context;
            private global::TestApp.Application.Links.ContextLinks? _Context;

            public Links(global::Hardened.Requests.Abstract.Links.ILinkContext context)
            {
                _context = context;
            }

            public global::TestApp.Application.Links.ContextLinks Context => _Context ??= new ContextLinks(_context);

            public sealed class ContextLinks
            {
                private readonly global::Hardened.Requests.Abstract.Links.ILinkContext _context;

                public ContextLinks(global::Hardened.Requests.Abstract.Links.ILinkContext context)
                {
                    _context = context;
                }

                public string WhoAmI()
                {
                    return _context.Resolve(global::TestApp.Application.Routes.Context.WhoAmI());
                }

                public string WhoAmIAbsolute()
                {
                    return _context.Absolute(global::TestApp.Application.Routes.Context.WhoAmI());
                }
            }
        }
    }
}
