// <auto-generated/>
#nullable enable
#pragma warning disable CS1591 // generated members carry no doc comments
namespace TestApp
{
    public partial class Application
    {

        /// <summary>
        /// The routes Application declares, as paths. For a link a client can call, use Application.Links.
        /// </summary>
        public static class Routes
        {

            public static class Clock
            {

                public static string Now()
                {
                    return "/now";
                }
            }
        }

        /// <summary>
        /// Links to Application's routes, as a client would call them. Resolve from the container, or read it off a template.
        /// </summary>
        public sealed class Links
        {
            private readonly global::Hardened.Requests.Abstract.Links.ILinkContext _context;
            private global::TestApp.Application.Links.ClockLinks? _Clock;

            public Links(global::Hardened.Requests.Abstract.Links.ILinkContext context)
            {
                _context = context;
            }

            public global::TestApp.Application.Links.ClockLinks Clock => _Clock ??= new ClockLinks(_context);

            public sealed class ClockLinks
            {
                private readonly global::Hardened.Requests.Abstract.Links.ILinkContext _context;

                public ClockLinks(global::Hardened.Requests.Abstract.Links.ILinkContext context)
                {
                    _context = context;
                }

                public string Now()
                {
                    return _context.Resolve(global::TestApp.Application.Routes.Clock.Now());
                }

                public string NowAbsolute()
                {
                    return _context.Absolute(global::TestApp.Application.Routes.Clock.Now());
                }
            }
        }
    }
}
