using System.Text;

namespace Hardened.Web.StaticContent.BuildTask;

/// <summary>
/// Writes a scan as the C# the application compiles.
/// </summary>
/// <remarks>
/// <para>
/// <b>Bytes go out as a <c>byte[]</c> initializer behind a span, not as a string.</b> A C# string
/// literal lives in the assembly's <c>#US</c> heap as UTF-16, so it costs two bytes per ASCII
/// character; base64 gives back a third of what compression saved. An all-constant <c>byte[]</c>
/// initializer is lowered by the compiler into a metadata blob - no per-element IL, no allocation
/// and nothing copied at startup - which is what <c>GZipLiteral</c> established for the OpenAPI
/// document and what this reuses the shape of.
/// </para>
/// <para>
/// <b>Deterministic.</b> Incremental builds and reproducible builds both require identical output
/// for identical input: files are emitted in a fixed order and <c>GZipStream</c> writes its MTIME
/// as zero, so nothing here varies between two builds of the same tree.
/// </para>
/// </remarks>
public static class ManifestEmitter {

    /// <summary>
    /// Bytes per emitted line. Long enough that a large asset is not thousands of lines, short
    /// enough that an editor opening the file is not asked to render one line of six figures.
    /// </summary>
    private const int BytesPerLine = 40;

    public static string Emit(ScanResult scan, string namespaceName, bool excludeFromCoverage) {
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("using DependencyModules.Runtime.Attributes;");
        builder.AppendLine("using Hardened.Web.StaticContent;");
        builder.AppendLine();
        builder.Append("namespace ").Append(namespaceName).AppendLine(";");
        builder.AppendLine();
        builder.AppendLine("/// <summary>");
        builder.AppendLine("/// What the build found in this application's static content directory.");
        builder.AppendLine("/// </summary>");
        builder.AppendLine("/// <remarks>");
        builder.AppendLine("/// Generated. Every edit here is overwritten by the next build.");
        builder.AppendLine("///");
        builder.AppendLine("/// Registered by attribute rather than by the package, because the bytes and");
        builder.AppendLine("/// the registration can only both exist in the assembly being compiled.");
        builder.AppendLine("/// </remarks>");

        if (excludeFromCoverage) {
            builder.AppendLine("[System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        }

        builder.AppendLine("[SingletonService(Using = RegistrationType.Try)]");
        builder.AppendLine("public sealed class GeneratedStaticContentManifest : IStaticContentManifest {");
        builder.AppendLine();

        EmitContentFields(builder, scan);

        builder.AppendLine("    private static readonly StaticContentManifestEntry[] _entries = {");

        foreach (var file in scan.Files) {
            EmitEntry(builder, file);
        }

        builder.AppendLine("    };");
        builder.AppendLine();
        builder.AppendLine(
            "    public global::System.Collections.Generic.IReadOnlyList<StaticContentManifestEntry> Entries => _entries;");
        builder.AppendLine();
        builder.Append("    public string? FallBackRoute => ")
            .Append(scan.FallBackRoute == null ? "null" : Literal(scan.FallBackRoute))
            .AppendLine(";");
        builder.AppendLine("}");

        return builder.ToString();
    }

    /// <summary>
    /// The bytes, one field per embedded representation.
    /// </summary>
    /// <remarks>
    /// Fields rather than inline initializers inside the entry array, so an alias - a directory
    /// route pointing at its default document - shares the array rather than emitting a second
    /// copy of it.
    /// </remarks>
    private static void EmitContentFields(StringBuilder builder, ScanResult scan) {
        var emitted = new HashSet<string>(StringComparer.Ordinal);

        foreach (var file in scan.Files) {
            if (file.Content == null || !emitted.Add(file.RelativePath)) {
                continue;
            }

            var name = FieldName(file.RelativePath);

            EmitByteArray(builder, name, file.Content);

            if (file.GZipContent != null) {
                EmitByteArray(builder, name + "Gz", file.GZipContent);
            }
        }
    }

    private static void EmitByteArray(StringBuilder builder, string name, byte[] bytes) {
        builder.Append("    private static readonly byte[] ").Append(name).Append(" = {");

        for (var index = 0; index < bytes.Length; index++) {
            if (index > 0) {
                builder.Append(',');
            }

            if (index % BytesPerLine == 0) {
                builder.Append("\n        ");
            }

            builder.Append(bytes[index]);
        }

        builder.AppendLine("\n    };");
        builder.AppendLine();
    }

    private static void EmitEntry(StringBuilder builder, ScannedFile file) {
        var name = file.Content == null ? null : FieldName(file.RelativePath);

        builder.Append("        new StaticContentManifestEntry(")
            .Append(Literal(file.RoutePath)).Append(", ")
            .Append(Literal(file.Hash)).Append(", ")
            .Append(file.Length).Append("L, ")
            .Append(file.LastModifiedUtcTicks).Append("L, ")
            .Append(name ?? "null").Append(", ")
            .Append(file.GZipContent == null ? "null" : name + "Gz").Append(", ")
            .Append(file.Content == null ? Literal(file.RelativePath) : "null")
            .AppendLine("),");
    }

    /// <summary>
    /// A field name derived from the path, and unique for it.
    /// </summary>
    /// <remarks>
    /// The readable part is truncated because a deep path makes an unreadable identifier either
    /// way; the hash suffix is what actually keeps two files apart, including two whose readable
    /// parts collide after truncation.
    /// </remarks>
    private static string FieldName(string relativePath) {
        var builder = new StringBuilder("_c");

        foreach (var character in relativePath.Take(40)) {
            builder.Append(char.IsLetterOrDigit(character) ? character : '_');
        }

        // Deterministic across runs and platforms, unlike string.GetHashCode.
        var hash = 2166136261u;

        foreach (var character in relativePath) {
            hash = (hash ^ character) * 16777619u;
        }

        return builder.Append('_').Append(hash.ToString("x8")).ToString();
    }

    private static string Literal(string value) {
        var builder = new StringBuilder("\"");

        foreach (var character in value) {
            builder.Append(character switch {
                '"' => "\\\"",
                '\\' => "\\\\",
                '\n' => "\\n",
                '\r' => "\\r",
                _ => character.ToString()
            });
        }

        return builder.Append('"').ToString();
    }
}
