// <auto-generated/>
#nullable enable
#pragma warning disable CS1591 // generated members carry no doc comments
using Hardened.Requests.Abstract.Links;
using TestApp;

namespace TestApp
{
    public partial class Application
    {

        /// <summary>
        /// The routes Application declares, as paths. For a link a client can call, use Application.Links.
        /// </summary>
        public static class Routes
        {

            public static class Blob
            {

                public static string BlobGet()
                {
                    return "/blob";
                }
            }
        }

        /// <summary>
        /// Links to Application's routes, as a client would call them. Resolve from the container, or read it off a template.
        /// </summary>
        public sealed class Links
        {
            private readonly global::Hardened.Requests.Abstract.Links.ILinkContext _context;
            private global::TestApp.Application.Links.BlobLinks? _Blob;

            public Links(global::Hardened.Requests.Abstract.Links.ILinkContext context)
            {
                _context = context;
            }

            public global::TestApp.Application.Links.BlobLinks Blob => _Blob ??= new BlobLinks(_context);

            public sealed class BlobLinks
            {
                private readonly global::Hardened.Requests.Abstract.Links.ILinkContext _context;

                public BlobLinks(global::Hardened.Requests.Abstract.Links.ILinkContext context)
                {
                    _context = context;
                }

                public string BlobGet()
                {
                    return _context.Resolve(global::TestApp.Application.Routes.Blob.BlobGet());
                }

                public string BlobGetAbsolute()
                {
                    return _context.Absolute(global::TestApp.Application.Routes.Blob.BlobGet());
                }
            }
        }
    }
}
