// <auto-generated/>
#nullable enable
#pragma warning disable CS1591 // generated members carry no doc comments
namespace TestApp.Generated
{
    public partial class BlobController_Blob : global::Hardened.Requests.Runtime.Execution.BaseExecutionHandler<global::TestApp.BlobController>
    {
        private static readonly global::Hardened.Requests.Runtime.Execution.ExecutionRequestHandlerInfo _handlerInfo =         new global::Hardened.Requests.Runtime.Execution.ExecutionRequestHandlerInfo("/blob", "GET", typeof(global::TestApp.BlobController), "Blob")
;

        public BlobController_Blob(global::System.IServiceProvider serviceProvider, string? routePath = null)
            : base(global::Hardened.Requests.Runtime.Execution.ExecutionHelper.AsyncStandardFilterEmptyParameters<global::TestApp.BlobController>(
            serviceProvider,
            _handlerInfo.WithPath(routePath),
            InvokeMethod,
            global::Hardened.Requests.Runtime.Execution.ExecutionHelper.GetFilterInfo()
        ), null)
        {
        }

        private static async global::System.Threading.Tasks.Task InvokeMethod(global::Hardened.Requests.Abstract.Execution.IExecutionContext context, global::TestApp.BlobController controller)
        {
            context.Response.ContentType = "application/octet-stream";
            context.Response.ResponseValue = await controller.Blob();
        }
    }
}
