// <auto-generated/>
#nullable enable
#pragma warning disable CS1591 // generated members carry no doc comments
namespace TestApp
{
    public partial class Application
    {

        /// <summary>
        /// The routes Application declares, as paths. For a link a client can call, use Application.Links.
        /// </summary>
        public static class Routes
        {

            public static class Upload
            {

                public static string UploadPost()
                {
                    return "/upload";
                }
            }
        }

        /// <summary>
        /// Links to Application's routes, as a client would call them. Resolve from the container, or read it off a template.
        /// </summary>
        public sealed class Links
        {
            private readonly global::Hardened.Web.Runtime.Links.ILinkContext _context;
            private global::TestApp.Application.Links.UploadLinks? _Upload;

            public Links(global::Hardened.Web.Runtime.Links.ILinkContext context)
            {
                _context = context;
            }

            public global::TestApp.Application.Links.UploadLinks Upload => _Upload ??= new UploadLinks(_context);

            public sealed class UploadLinks
            {
                private readonly global::Hardened.Web.Runtime.Links.ILinkContext _context;

                public UploadLinks(global::Hardened.Web.Runtime.Links.ILinkContext context)
                {
                    _context = context;
                }

                public string UploadPost()
                {
                    return _context.Resolve(global::TestApp.Application.Routes.Upload.UploadPost());
                }

                public string UploadPostAbsolute()
                {
                    return _context.Absolute(global::TestApp.Application.Routes.Upload.UploadPost());
                }
            }
        }
    }
}
