// <auto-generated/>
#nullable enable
#pragma warning disable CS1591 // generated members carry no doc comments
namespace TestApp.Generated
{
    public partial class UploadController_Upload_1556 : global::Hardened.Requests.Runtime.Execution.BaseExecutionHandler<global::TestApp.UploadController>
    {
        private static readonly global::Hardened.Requests.Abstract.Execution.IExecutionRequestParameter[] _parameterInfo =         CreateParameterInfo()
;
        private static readonly global::Hardened.Requests.Runtime.Execution.ExecutionRequestHandlerInfo _handlerInfo =         new global::Hardened.Requests.Runtime.Execution.ExecutionRequestHandlerInfo("/upload", "POST", typeof(global::TestApp.UploadController), "Upload", _parameterInfo)
;

        public UploadController_Upload_1556(global::System.IServiceProvider serviceProvider, string? routePath = null)
            : base(global::Hardened.Requests.Runtime.Execution.ExecutionHelper.AsyncStandardFilterWithParameters<
            global::TestApp.UploadController,
            global::TestApp.Generated.UploadController_Upload_1556.Parameters
        >(
            serviceProvider,
            _handlerInfo.WithPath(routePath),
            BindRequestParameters,
            InvokeMethod,
            global::Hardened.Requests.Runtime.Execution.ExecutionHelper.GetFilterInfo()
        ), null)
        {
        }

        private static global::Hardened.Requests.Abstract.Execution.IExecutionRequestParameter[] CreateParameterInfo()
        {
            var returnArray = new global::Hardened.Requests.Abstract.Execution.IExecutionRequestParameter[2];
            returnArray[0] = new global::Hardened.Requests.Runtime.Execution.ExecutionRequestParameter(
                "upload",
                0,
                typeof(global::TestApp.Upload)
            );
            returnArray[1] = new global::Hardened.Requests.Runtime.Execution.ExecutionRequestParameter(
                "extras",
                1,
                typeof(global::System.Collections.Generic.IReadOnlyList<global::Hardened.Requests.Abstract.Forms.IFormFile>)
            );
            return returnArray;
        }

        private static async global::System.Threading.Tasks.Task InvokeMethod(global::Hardened.Requests.Abstract.Execution.IExecutionContext context, global::TestApp.UploadController controller, global::TestApp.Generated.UploadController_Upload_1556.Parameters parameters)
        {
            context.Response.ResponseValue = await controller.Upload(
                parameters.upload,
                parameters.extras
            );
        }

        private static async global::System.Threading.Tasks.Task<global::Hardened.Requests.Abstract.Execution.IExecutionRequestParameters> BindRequestParameters(global::Hardened.Requests.Abstract.Execution.IExecutionContext context)
        {
            var parameters = new global::TestApp.Generated.UploadController_Upload_1556.Parameters();
            var form = await context.KnownServices.FormReader.ReadForm(context);
            var uploadModel = new global::TestApp.Upload(
                context.KnownServices.StringConverterService.ParseRequired<string>(
                    form.Get("tenant")!,
                    "tenant"
                ),
                global::Hardened.Requests.Runtime.Forms.FormFileBinding.Required(
                    form.GetFile("file"),
                    "file"
                )
            );
            parameters.upload = uploadModel;
            parameters.extras = global::Hardened.Requests.Runtime.Forms.FormFileBinding.OptionalMany(form.GetFiles("extras"));
            return parameters;
        }

        public partial class Parameters : global::Hardened.Requests.Runtime.Execution.ExecutionRequestParameters
        {

            public global::TestApp.Upload upload { get; set; } = default!;

            public global::System.Collections.Generic.IReadOnlyList<global::Hardened.Requests.Abstract.Forms.IFormFile>? extras { get; set; } = default!;

            public override object this[int index]
            {
                get
                {
                    switch (index)
                    {
                        case 0:
                            return this.upload!;
                        case 1:
                            return this.extras!;
                    }
                    throw new global::System.IndexOutOfRangeException("Index out of range, parameters count 2, index was " + index);
                }
                set
                {
                    switch (index)
                    {
                        case 0:
                            this.upload = (global::TestApp.Upload)value;
                            return;
                        case 1:
                            this.extras = (global::System.Collections.Generic.IReadOnlyList<global::Hardened.Requests.Abstract.Forms.IFormFile>?)value;
                            return;
                    }
                    throw new global::System.IndexOutOfRangeException("Index out of range, parameters count 2, index was " + index);
                }
            }

            public override global::System.Collections.Generic.IReadOnlyList<global::Hardened.Requests.Abstract.Execution.IExecutionRequestParameter> Info => _parameterInfo;
        }
    }
}
