<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(HardenedTargetFramework)</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Hardened.SourceGeneration.Testing\Hardened.SourceGeneration.Testing.csproj"/>
    </ItemGroup>

</Project>
