<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Description>Execution pipeline implementation for Hardened: filters, serialization, parameter validation and error handling.</Description>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>True</IsPackable>
        <PackageId>Hardened.Requests.Runtime</PackageId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="DependencyModules.Runtime" Version="1.0.0-rc9220" />
        <PackageReference Include="DependencyModules.SourceGenerator" Version="1.0.0-rc9220" OutputItemType="Analyzer" ReferenceOutputAssembly="false" PrivateAssets="all" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.1" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.1" />
        <PackageReference Include="Microsoft.Extensions.Primitives" Version="8.0.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Shared\Hardened.Shared.Runtime\Hardened.Shared.Runtime.csproj"/>
        <ProjectReference Include="..\Hardened.Requests.Abstract\Hardened.Requests.Abstract.csproj"/>
    </ItemGroup>

</Project>
