<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Amazon.Lambda.DynamoDBEvents" Version="3.1.1" />
        <PackageReference Include="Hardened.Library.SourceGenerator" Version="0.2.0-Alpha11" />
        <PackageReference Include="Hardened.Requests.Runtime" Version="0.2.0-Alpha11" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Function\Hardened.Amz.Function.Lambda.Runtime\Hardened.Amz.Function.Lambda.Runtime.csproj" />
    </ItemGroup>
</Project>
