// <auto-generated/>
#nullable enable
#pragma warning disable CS1591 // generated members carry no doc comments
namespace TestApp.Generated
{
    public partial class SearchController_List_754 : global::Hardened.Requests.Runtime.Execution.BaseExecutionHandler<global::TestApp.SearchController>
    {
        private static readonly global::Hardened.Requests.Abstract.Execution.IExecutionRequestParameter[] _parameterInfo =         CreateParameterInfo()
;
        private static readonly global::Hardened.Requests.Runtime.Execution.ExecutionRequestHandlerInfo _handlerInfo =         new global::Hardened.Requests.Runtime.Execution.ExecutionRequestHandlerInfo("/list", "GET", typeof(global::TestApp.SearchController), "List", _parameterInfo)
;

        public SearchController_List_754(global::System.IServiceProvider serviceProvider, string? routePath = null)
            : base(global::Hardened.Requests.Runtime.Execution.ExecutionHelper.AsyncStandardFilterWithParameters<
            global::TestApp.SearchController,
            global::TestApp.Generated.SearchController_List_754.Parameters
        >(
            serviceProvider,
            _handlerInfo.WithPath(routePath),
            BindRequestParameters,
            InvokeMethod,
            global::Hardened.Requests.Runtime.Execution.ExecutionHelper.GetFilterInfo()
        ), null)
        {
        }

        private static global::Hardened.Requests.Abstract.Execution.IExecutionRequestParameter[] CreateParameterInfo()
        {
            var returnArray = new global::Hardened.Requests.Abstract.Execution.IExecutionRequestParameter[1];
            returnArray[0] = new global::Hardened.Requests.Runtime.Execution.ExecutionRequestParameter(
                "paging",
                0,
                typeof(global::TestApp.Paging)
            );
            return returnArray;
        }

        private static async global::System.Threading.Tasks.Task InvokeMethod(global::Hardened.Requests.Abstract.Execution.IExecutionContext context, global::TestApp.SearchController controller, global::TestApp.Generated.SearchController_List_754.Parameters parameters)
        {
            context.Response.ResponseValue = await controller.List(parameters.paging);
        }

        private static global::System.Threading.Tasks.Task<global::Hardened.Requests.Abstract.Execution.IExecutionRequestParameters> BindRequestParameters(global::Hardened.Requests.Abstract.Execution.IExecutionContext context)
        {
            var parameters = new global::TestApp.Generated.SearchController_List_754.Parameters();
            var pagingModel = new global::TestApp.Paging { Sort = context.KnownServices.StringConverterService.ParseRequired<string>(
                context.Request.QueryString.Get("sort")!,
                "sort"
            ) };
            pagingModel.Page = context.KnownServices.StringConverterService.ParseRequired<int>(
                context.Request.QueryString.Get("page")!,
                "page"
            );
            if (!global::Microsoft.Extensions.Primitives.StringValues.IsNullOrEmpty(context.Request.QueryString.Get("size")))
            {
                pagingModel.Size = context.KnownServices.StringConverterService.ParseRequired<int>(
                    context.Request.QueryString.Get("size")!,
                    "size"
                );
            }
            parameters.paging = pagingModel;
            return global::System.Threading.Tasks.Task.FromResult<global::Hardened.Requests.Abstract.Execution.IExecutionRequestParameters>(parameters);
        }

        public partial class Parameters : global::Hardened.Requests.Runtime.Execution.ExecutionRequestParameters
        {

            public global::TestApp.Paging paging { get; set; } = default!;

            public override object this[int index]
            {
                get
                {
                    switch (index)
                    {
                        case 0:
                            return this.paging!;
                    }
                    throw new global::System.IndexOutOfRangeException("Index out of range, parameters count 1, index was " + index);
                }
                set
                {
                    switch (index)
                    {
                        case 0:
                            this.paging = (global::TestApp.Paging)value;
                            return;
                    }
                    throw new global::System.IndexOutOfRangeException("Index out of range, parameters count 1, index was " + index);
                }
            }

            public override global::System.Collections.Generic.IReadOnlyList<global::Hardened.Requests.Abstract.Execution.IExecutionRequestParameter> Info => _parameterInfo;
        }
    }
}
