// <auto-generated/>
#nullable enable
#pragma warning disable CS1591 // generated members carry no doc comments
namespace TestApp.Generated
{
    public partial class SearchController_Search_754 : global::Hardened.Requests.Runtime.Execution.BaseExecutionHandler<global::TestApp.SearchController>
    {
        private static readonly global::Hardened.Requests.Abstract.Execution.IExecutionRequestParameter[] _parameterInfo =         CreateParameterInfo()
;
        private static readonly global::Hardened.Requests.Runtime.Execution.ExecutionRequestHandlerInfo _handlerInfo =         new global::Hardened.Requests.Runtime.Execution.ExecutionRequestHandlerInfo("/search", "POST", typeof(global::TestApp.SearchController), "Search", _parameterInfo)
;

        public SearchController_Search_754(global::System.IServiceProvider serviceProvider, string? routePath = null)
            : base(global::Hardened.Requests.Runtime.Execution.ExecutionHelper.AsyncStandardFilterWithParameters<
            global::TestApp.SearchController,
            global::TestApp.Generated.SearchController_Search_754.Parameters
        >(
            serviceProvider,
            _handlerInfo.WithPath(routePath),
            BindRequestParameters,
            InvokeMethod,
            global::Hardened.Requests.Runtime.Execution.ExecutionHelper.GetFilterInfo()
        ), null)
        {
        }

        private static global::Hardened.Requests.Abstract.Execution.IExecutionRequestParameter[] CreateParameterInfo()
        {
            var returnArray = new global::Hardened.Requests.Abstract.Execution.IExecutionRequestParameter[1];
            returnArray[0] = new global::Hardened.Requests.Runtime.Execution.ExecutionRequestParameter(
                "search",
                0,
                typeof(global::TestApp.Search)
            );
            return returnArray;
        }

        private static async global::System.Threading.Tasks.Task InvokeMethod(global::Hardened.Requests.Abstract.Execution.IExecutionContext context, global::TestApp.SearchController controller, global::TestApp.Generated.SearchController_Search_754.Parameters parameters)
        {
            context.Response.ResponseValue = await controller.Search(parameters.search);
        }

        private static async global::System.Threading.Tasks.Task<global::Hardened.Requests.Abstract.Execution.IExecutionRequestParameters> BindRequestParameters(global::Hardened.Requests.Abstract.Execution.IExecutionContext context)
        {
            var parameters = new global::TestApp.Generated.SearchController_Search_754.Parameters();
            var form = await global::Hardened.Requests.Runtime.Forms.FormBinding.Read(context);
            var searchModel = new global::TestApp.Search(
                context.KnownServices.StringConverterService.ParseRequired<int>(
                    form.Get("page")!,
                    "page"
                ),
                context.KnownServices.StringConverterService.ParseRequired<string>(
                    form.Get("q")!,
                    "q"
                ),
                context.KnownServices.StringConverterService.ParseWithDefault<int>(
                    form.Get("size")!,
                    "size",
                    20
                )
            );
            parameters.search = searchModel;
            return parameters;
        }

        public partial class Parameters : global::Hardened.Requests.Runtime.Execution.ExecutionRequestParameters
        {

            public global::TestApp.Search search { get; set; } = default!;

            public override object this[int index]
            {
                get
                {
                    switch (index)
                    {
                        case 0:
                            return this.search!;
                    }
                    throw new global::System.IndexOutOfRangeException("Index out of range, parameters count 1, index was " + index);
                }
                set
                {
                    switch (index)
                    {
                        case 0:
                            this.search = (global::TestApp.Search)value;
                            return;
                    }
                    throw new global::System.IndexOutOfRangeException("Index out of range, parameters count 1, index was " + index);
                }
            }

            public override global::System.Collections.Generic.IReadOnlyList<global::Hardened.Requests.Abstract.Execution.IExecutionRequestParameter> Info => _parameterInfo;
        }
    }
}
