// <auto-generated/>
#nullable enable
#pragma warning disable CS1591 // generated members carry no doc comments
using Hardened.Requests.Abstract.Links;
using System;
using TestApp;

namespace TestApp
{
    public partial class Application
    {

        /// <summary>
        /// The routes Application declares, as paths. For a link a client can call, use Application.Links.
        /// </summary>
        public static class Routes
        {

            public static class Widget
            {

                public static string Create()
                {
                    return "/widgets";
                }

                public static string Find(global::System.String id)
                {
                    return "/widgets/" + global::System.Uri.EscapeDataString(id);
                }
            }
        }

        /// <summary>
        /// Links to Application's routes, as a client would call them. Resolve from the container, or read it off a template.
        /// </summary>
        public sealed class Links
        {
            private readonly global::Hardened.Requests.Abstract.Links.ILinkContext _context;
            private global::TestApp.Application.Links.WidgetLinks? _Widget;

            public Links(global::Hardened.Requests.Abstract.Links.ILinkContext context)
            {
                _context = context;
            }

            public global::TestApp.Application.Links.WidgetLinks Widget => _Widget ??= new WidgetLinks(_context);

            public sealed class WidgetLinks
            {
                private readonly global::Hardened.Requests.Abstract.Links.ILinkContext _context;

                public WidgetLinks(global::Hardened.Requests.Abstract.Links.ILinkContext context)
                {
                    _context = context;
                }

                public string Create()
                {
                    return _context.Resolve(global::TestApp.Application.Routes.Widget.Create());
                }

                public string CreateAbsolute()
                {
                    return _context.Absolute(global::TestApp.Application.Routes.Widget.Create());
                }

                public string Find(global::System.String id)
                {
                    return _context.Resolve(global::TestApp.Application.Routes.Widget.Find(id));
                }

                public string FindAbsolute(global::System.String id)
                {
                    return _context.Absolute(global::TestApp.Application.Routes.Widget.Find(id));
                }
            }
        }
    }
}
