// <auto-generated/>
#nullable enable
#pragma warning disable CS1591 // generated members carry no doc comments
using DependencyModules.Runtime.Helpers;
using Hardened.Requests.Abstract.Execution;
using Hardened.Requests.Abstract.PathTokens;
using Hardened.Web.Runtime.Handlers;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Diagnostics.CodeAnalysis;
using TestApp.Generated;

namespace TestApp
{
    public partial class Application
    {
        [DynamicDependency(nameof(RoutingTableDI))]
        private static int _routingTableDependencies =         DependencyRegistry<Application>.Add(RoutingTableDI)
;

        private static void RoutingTableDI(IServiceCollection serviceCollection)
        {
            serviceCollection.AddSingleton<
                IWebExecutionRequestHandlerProvider,
                Application.RoutingTable
            >();
            serviceCollection.AddTransient<TicketController>();
            serviceCollection.AddTransient<Application.Links>();
        }

        private class RoutingTable : IWebExecutionRequestHandlerProvider
        {
            private IServiceProvider _rootServiceProvider;
            private static readonly string[] _pathTokenNamesTicketController_Get_329 =             new string[] { "id" }
;
            private RequestHandlerInfo? _infoTicketController_Get_329;
            private static readonly string[] _pathTokenNamesTicketController_Replace_329 =             new string[] { "id" }
;
            private RequestHandlerInfo? _infoTicketController_Replace_329;
            private static readonly string[] _pathTokenNamesTicketController_Remove_329 =             new string[] { "id" }
;
            private RequestHandlerInfo? _infoTicketController_Remove_329;
            private static readonly RequestHandlerInfo _methodNotAllowedDELETEGETHEADPUT =             global::Hardened.Web.Runtime.Handlers.RequestHandlerInfo.MethodNotAllowed("DELETE, GET, HEAD, PUT")
;

            public RoutingTable(IServiceProvider serviceProvider)
            {
                _rootServiceProvider = serviceProvider;
            }

            public RequestHandlerInfo? GetExecutionRequestHandler(IExecutionContext context, ref PathTokenCollection pathTokens)
            {
                var pathSpan = context.Request.Path.AsSpan();
                return TestPath_SlashticketsSlash(
                    pathSpan,
                    0,
                    context.Request.Method,
                    ref pathTokens
                );
            }

            public RequestHandlerInfo? TestPath_SlashticketsSlash(ReadOnlySpan<char> charSpan, int index, string methodString, ref PathTokenCollection pathTokens)
            {
                RequestHandlerInfo? handlerInfo = null;
                if ((charSpan.Length >= index + 9) && charSpan.Slice(index, 9).SequenceEqual("/tickets/"))
                {
                    index += 9;
                    if (handlerInfo == null)
                    {
                        handlerInfo = TestPath_ticketsSlashWildCard(
                            charSpan,
                            index,
                            methodString,
                            ref pathTokens
                        );
                    }
                }
                return handlerInfo;
            }

            public RequestHandlerInfo? TestPath_ticketsSlashWildCard(ReadOnlySpan<char> charSpan, int index, string methodString, ref PathTokenCollection pathTokens)
            {
                RequestHandlerInfo? handlerInfo = null;
                handlerInfo = TestPath_NoPathWildCardMatch(
                    charSpan,
                    index,
                    methodString,
                    ref pathTokens
                );
                return handlerInfo;
            }

            public RequestHandlerInfo? TestPath_NoPathWildCardMatch(ReadOnlySpan<char> charSpan, int index, string methodString, ref PathTokenCollection pathTokens)
            {
                if (charSpan.Length <= index)
                {
                    return null;
                }
                if (charSpan.Slice(index).IndexOf('/') >= 0)
                {
                    return null;
                }
                switch (methodString)
                {
                    case "HEAD":
                    case "GET":
                        pathTokens = new PathTokenCollection(
                            _pathTokenNamesTicketController_Get_329,
                            charSpan.Slice(index).ToString()
                        );
                        return _infoTicketController_Get_329 ??= new RequestHandlerInfo(new TicketController_Get_329(_rootServiceProvider));
                    case "PUT":
                        pathTokens = new PathTokenCollection(
                            _pathTokenNamesTicketController_Replace_329,
                            charSpan.Slice(index).ToString()
                        );
                        return _infoTicketController_Replace_329 ??= new RequestHandlerInfo(new TicketController_Replace_329(_rootServiceProvider));
                    case "DELETE":
                        pathTokens = new PathTokenCollection(
                            _pathTokenNamesTicketController_Remove_329,
                            charSpan.Slice(index).ToString()
                        );
                        return _infoTicketController_Remove_329 ??= new RequestHandlerInfo(new TicketController_Remove_329(_rootServiceProvider));
                    default:
                        return _methodNotAllowedDELETEGETHEADPUT;
                }
            }
        }
    }
}
