// <auto-generated/>
#nullable enable
#pragma warning disable CS1591 // generated members carry no doc comments
using Hardened.Requests.Abstract.Links;
using System;
using TestApp;

namespace TestApp
{
    public partial class Application
    {

        /// <summary>
        /// The routes Application declares, as paths. For a link a client can call, use Application.Links.
        /// </summary>
        public static class Routes
        {

            public static class Ticket
            {

                public static string Remove(global::System.String id)
                {
                    return "/tickets/" + global::System.Uri.EscapeDataString(id);
                }

                public static string Get(global::System.String id)
                {
                    return "/tickets/" + global::System.Uri.EscapeDataString(id);
                }

                public static string Replace(global::System.String id)
                {
                    return "/tickets/" + global::System.Uri.EscapeDataString(id);
                }
            }
        }

        /// <summary>
        /// Links to Application's routes, as a client would call them. Resolve from the container, or read it off a template.
        /// </summary>
        public sealed class Links
        {
            private readonly global::Hardened.Requests.Abstract.Links.ILinkContext _context;
            private global::TestApp.Application.Links.TicketLinks? _Ticket;

            public Links(global::Hardened.Requests.Abstract.Links.ILinkContext context)
            {
                _context = context;
            }

            public global::TestApp.Application.Links.TicketLinks Ticket => _Ticket ??= new TicketLinks(_context);

            public sealed class TicketLinks
            {
                private readonly global::Hardened.Requests.Abstract.Links.ILinkContext _context;

                public TicketLinks(global::Hardened.Requests.Abstract.Links.ILinkContext context)
                {
                    _context = context;
                }

                public string Remove(global::System.String id)
                {
                    return _context.Resolve(global::TestApp.Application.Routes.Ticket.Remove(id));
                }

                public string RemoveAbsolute(global::System.String id)
                {
                    return _context.Absolute(global::TestApp.Application.Routes.Ticket.Remove(id));
                }

                public string Get(global::System.String id)
                {
                    return _context.Resolve(global::TestApp.Application.Routes.Ticket.Get(id));
                }

                public string GetAbsolute(global::System.String id)
                {
                    return _context.Absolute(global::TestApp.Application.Routes.Ticket.Get(id));
                }

                public string Replace(global::System.String id)
                {
                    return _context.Resolve(global::TestApp.Application.Routes.Ticket.Replace(id));
                }

                public string ReplaceAbsolute(global::System.String id)
                {
                    return _context.Absolute(global::TestApp.Application.Routes.Ticket.Replace(id));
                }
            }
        }
    }
}
