using Hardened.IntegrationTests.Smithy.SUT.Models;
using Hardened.IntegrationTests.Smithy.SUT.Services;
using Hardened.Requests.Abstract.Attributes;

namespace Hardened.IntegrationTests.Smithy.SUT;

/// <summary>
/// Implements the interface generated from an awsJson1_0 model, in the same application as the
/// path-routed one next door.
/// </summary>
/// <remarks>
/// <para>
/// Both services are generated by the same emitters from the same IR; the only thing that differs is
/// how a request names an operation. Here it is a <c>POST /</c> with an <c>X-Amz-Target</c> header,
/// so neither method has a path parameter and each takes its whole input structure as the body -
/// which is what the protocol says and what makes it cheaper to serve than restJson1, not harder.
/// </para>
/// <para>
/// That the two coexist is the point. One routing table answers both, and it consults the header
/// before the route tree because every operation here would otherwise collide on <c>POST /</c>.
/// </para>
/// </remarks>
[Handler]
public class BankServiceImpl : IBankService {

    private static readonly Dictionary<string, long> Balances = new() {
        ["acct-1"] = 125_00,
        ["acct-2"] = 4_250_00
    };

    /// <summary>
    /// Throws the error the model declares, which is how a declared failure reaches the wire.
    /// </summary>
    /// <remarks>
    /// The signature still returns a balance. <c>AccountNotFoundException</c> is named for the error
    /// shape the model declares rather than for this operation, so <c>Transfer</c> - which binds the
    /// same shape - throws the same type, and an AWS-generated client built from this model calls
    /// the error what the server does. Its payload is the <c>AccountNotFound</c> record, to which
    /// the reader added the <c>__type</c> field the protocol identifies errors by, so nothing here
    /// has to know that awsJson wants one.
    /// </remarks>
    public Task<GetBalanceOutput> GetBalance(GetBalanceInput body) {
        if (!Balances.TryGetValue(body.AccountId, out var cents)) {
            // AsException() rather than naming AccountNotFound twice, which is the same shorthand
            // the shipped records get and is generated because this shape names one error.
            throw new AccountNotFound($"No account {body.AccountId}.").AsException();
        }

        return Task.FromResult(new GetBalanceOutput(cents, "USD"));
    }

    public Task<TransferOutput> Transfer(TransferInput body) =>
        Task.FromResult(new TransferOutput($"{body.FromAccount}->{body.ToAccount}:{body.AmountCents}"));
}
