using Hardened.IntegrationTests.Smithy.SUT.Models;
using Hardened.IntegrationTests.Smithy.SUT.Services;
using Hardened.Requests.Abstract.Attributes;

namespace Hardened.IntegrationTests.Smithy.SUT;

/// <summary>
/// Implements the interface generated from an awsJson1_0 model, in the same application as the
/// path-routed one next door.
/// </summary>
/// <remarks>
/// <para>
/// Both services are generated by the same emitters from the same IR; the only thing that differs is
/// how a request names an operation. Here it is a <c>POST /</c> with an <c>X-Amz-Target</c> header,
/// so neither method has a path parameter and each takes its whole input structure as the body -
/// which is what the protocol says and what makes it cheaper to serve than restJson1, not harder.
/// </para>
/// <para>
/// That the two coexist is the point. One routing table answers both, and it consults the header
/// before the route tree because every operation here would otherwise collide on <c>POST /</c>.
/// </para>
/// </remarks>
[Handler]
public class BankServiceImpl : IBankService {

    private static readonly Dictionary<string, long> Balances = new() {
        ["acct-1"] = 125_00,
        ["acct-2"] = 4_250_00
    };

    public Task<GetBalanceOutput> GetBalance(GetBalanceInput body) =>
        Task.FromResult(new GetBalanceOutput(
            Balances.TryGetValue(body.AccountId, out var cents) ? cents : 0, "USD"));

    public Task<TransferOutput> Transfer(TransferInput body) =>
        Task.FromResult(new TransferOutput($"{body.FromAccount}->{body.ToAccount}:{body.AmountCents}"));
}
