using Hardened.Library.SourceGenerator;
using Hardened.Requests.Abstract.Attributes;
using Hardened.SourceGeneration.Testing;
using Hardened.Web.Runtime.Attributes;
using Microsoft.CodeAnalysis;
using Xunit;

namespace Hardened.Web.SourceGenerator.Tests.Routing;

/// <summary>
/// Two routing generators over one compilation.
/// </summary>
/// <remarks>
/// <para>
/// OR-06. A code-first module project referenced from the specification-first library ran both
/// generator sets over the library's compilation. Each emitted a routing table, a links type and a
/// handler class per operation, so every generated name was declared twice - a screen of CS0102 and
/// CS0111 pointing into <c>obj/**/generated/**</c>, naming the duplicated members and never the
/// reference that brought the second generator.
/// </para>
/// <para>
/// The second generator here is a stand-in rather than <c>Hardened.Idl.SourceGenerator</c>, which
/// this assembly does not reference. What makes a generator a routing generator, as far as the
/// check is concerned, is that it declares the marker - so a stand-in that declares it is the
/// condition under test, and it holds for whichever pair of generators arrives.
/// </para>
/// </remarks>
public class CollidingRoutingGeneratorsTests {
    private const string DiagnosticId = "HRDR008";

    private static readonly Type[] Anchors = [
        typeof(GetAttribute),       // Hardened.Web.Runtime
        typeof(FromBodyAttribute)   // Hardened.Requests.Abstract
    ];

    private const string Source = """
        using Hardened.Shared.Runtime.Attributes;
        using Hardened.Web.Runtime.Attributes;

        namespace TestApp;

        [HardenedModule]
        [HardenedWebModule]
        public partial class TestApplication { }

        public class ItemController {
            [Get("/items/{id}")]
            public string Item(string id) => id;
        }
        """;

    /// <summary>
    /// A second routing generator, declaring the marker the way both real ones do.
    /// </summary>
    /// <remarks>
    /// The marker is written out here rather than taken from <c>RoutingGeneratorMarker</c>: this
    /// assembly compiles the shared source into three referenced generators, so the type is
    /// ambiguous by name. Written out, the test also fails if the real marker stops being partial.
    /// </remarks>
    private sealed class SecondRoutingGenerator : IIncrementalGenerator {
        public void Initialize(IncrementalGeneratorInitializationContext context) =>
            context.RegisterPostInitializationOutput(static production => production.AddSource(
                "Hardened.Web.Marker.g.cs",
                """
                // <auto-generated/>
                #nullable enable
                namespace Hardened.Web.Generated {
                    internal static partial class WebRoutingGeneratorMarker {
                    }
                }
                """));
    }

    private static GeneratorResult Generate(params IIncrementalGenerator[] generators) =>
        GeneratorTestHarness.Run(
            new Dictionary<string, string> { ["Test.cs"] = Source }, generators, Anchors);

    private static Diagnostic? Reported(GeneratorResult result) =>
        result.GeneratorDiagnostics.SingleOrDefault(reported => reported.Id == DiagnosticId);

    [Fact]
    public void TwoRoutingGeneratorsAreAnError() {
        var diagnostic = Reported(Generate(
            new LibrarySourceGenerator(),
            new WebLibrarySourceGenerator(),
            new SecondRoutingGenerator()));

        Assert.NotNull(diagnostic);
        Assert.Equal(DiagnosticSeverity.Error, diagnostic.Severity);
    }

    /// <summary>
    /// The fix is on a reference rather than in the code, so the message has to name the
    /// generators and the attribute that stops one travelling.
    /// </summary>
    [Fact]
    public void TheMessageNamesBothGeneratorsAndTheFix() {
        var message = Reported(Generate(
            new LibrarySourceGenerator(),
            new WebLibrarySourceGenerator(),
            new SecondRoutingGenerator()))!.GetMessage();

        // The stand-in generator is compiled into this test assembly, so that is the name Roslyn
        // gives its generated files and the name the message reads back.
        Assert.Contains(
            "Hardened.Web.SourceGenerator and Hardened.Web.SourceGenerator.Tests", message);
        Assert.Contains("PrivateAssets=\"all\"", message);
        Assert.Contains("ProjectReference", message);
    }

    /// <summary>One routing generator is the ordinary case, and says nothing.</summary>
    [Fact]
    public void OneRoutingGeneratorIsNotReported() =>
        Assert.Null(Reported(Generate(
            new LibrarySourceGenerator(), new WebLibrarySourceGenerator())));

    /// <summary>And so is none, which is HRDR006's business rather than this one's.</summary>
    [Fact]
    public void NoRoutingGeneratorIsNotReported() =>
        Assert.Null(Reported(Generate(new LibrarySourceGenerator())));

    /// <summary>
    /// Two declarations of the marker have to merge rather than collide. Left non-partial, the
    /// second declaration was a CS0101 in a generated file - one more error saying nothing about
    /// why there were two.
    /// </summary>
    /// <remarks>
    /// Asserted as "no error mentions the marker" rather than as a list of ids, because the id
    /// depends on what the other declaration says: two plain declarations are CS0101, and one
    /// plain beside one partial is CS0260. Naming either lets the other through.
    /// </remarks>
    [Fact]
    public void TheMarkerItselfDoesNotCollide() {
        var result = Generate(
            new LibrarySourceGenerator(),
            new WebLibrarySourceGenerator(),
            new SecondRoutingGenerator());

        var errors = result.CompilationDiagnostics
            .Where(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
            .Where(diagnostic => diagnostic.GetMessage().Contains("WebRoutingGeneratorMarker"))
            .Select(diagnostic => diagnostic.Id + ": " + diagnostic.GetMessage())
            .ToList();

        Assert.True(errors.Count == 0, string.Join(" | ", errors));
    }

    /// <summary>
    /// The generator's name is the third path segment from the end, never the first. With
    /// <c>EmitCompilerGeneratedFiles</c> on - the templates turn it on - a generated tree's path is
    /// absolute, so reading the first segment made every generator <c>Users</c> and a
    /// distinct-count of one reported nothing. That is how this diagnostic sat silent through the
    /// 0.20 trial's two-generator build.
    /// </summary>
    [Theory]
    [InlineData(
        "/Users/someone/app/obj/Debug/net8.0/generated/Hardened.Idl.SourceGenerator/Hardened.Idl.SourceGenerator.SpecSourceGenerator/Hardened.Web.Marker.g.cs",
        "Hardened.Idl.SourceGenerator")]
    [InlineData(
        "C:\\app\\obj\\Debug\\net8.0\\generated\\Hardened.Web.SourceGenerator\\Hardened.Web.SourceGenerator.WebLibrarySourceGenerator\\Hardened.Web.Marker.g.cs",
        "Hardened.Web.SourceGenerator")]
    [InlineData(
        "Hardened.Web.SourceGenerator/Hardened.Web.SourceGenerator.WebLibrarySourceGenerator/Hardened.Web.Marker.g.cs",
        "Hardened.Web.SourceGenerator")]
    [InlineData("Hardened.Web.Marker.g.cs", "an unnamed generator")]
    public void TheGeneratorIsNamedFromTheEndOfThePath(string path, string expected) =>
        Assert.Equal(expected, CollidingRoutingGenerators.GeneratorName(path));
}
